### ISSUE TITLE
trust level not getting to 100%

### ISSUE THREAD

**Issue by geckah** [MrPlusGH/NPlusMiner#1]
I've left it running for 8 hours, however the trust level only got to 37% and it says 00 days 02:13.
The zpool balance is updating but it seems like all the other figures have frozen.

**Comment by MrPlusGH** [comment]
Are you sure the balance is updating while not other data.
I'm looking if any issue when the tracker fails. But if it does. Nothing should get updated.

Just to confirm. This is using the latest release?

**Comment by geckah** [comment]
I'm sorry i wasn't clear - The miner is not updating my wallet's balance,.
Yes i'm using the master copy

edit: i see that there were changes to the master copy since i've downloaded it. I will re-download and test it out

**Comment by MrPlusGH** [comment]
Please use latest release and let me know.

**Comment by MrPlusGH** [comment]
Looks ok for me. Please reopen if necessary.
