### ISSUE TITLE
v2.0 or 2.01?

### ISSUE THREAD

**Issue by rander2009** [MrPlusGH/NPlusMiner#10]
Hello, apologies if i'm mistaken.  When I download 2.01 from here and set it up, there is an indicator on the GUI that version 2.01 is available for download.

Also, can we display the current BTC & LTC prices on the GUI? just an idea.

**Comment by MrPlusGH** [comment]
Forgot to update the version :(
You are effectively using 2.0.1
Will fix and update the release and let you know here once done.

**Comment by rander2009** [comment]
Thank you Sir.

**Comment by MrPlusGH** [comment]
Updated the release. You can re-download from [Releases](https://github.com/MrPlusGH/NPlusMiner/releases)

**Comment by rander2009** [comment]
You're Awesome!
