### ISSUE TITLE
CPU miner

### ISSUE THREAD

**Issue by RetroShag** [MrPlusGH/NPlusMiner#100]
Just a suggestion, add --cpu-affinity AAAA argument to JayDDee cpu miner to spread the load across all cores, and not just the first ones.

**Comment by MrPlusGH** [comment]
AAAA would spread across half the cores if I get this right.
Do you see any gain in hashrate using this config?

**Comment by RetroShag** [comment]
Yes, it does improve the hashrate.  Spreading the load across all cores ensures that all CPU cache is utilized.
I usee AAAA on Ryzen 1700 (16 threads), but it should work on other cpus.

**Comment by MrPlusGH** [comment]
Thank you.
Will put in test.

**Comment by MrPlusGH** [comment]
https://github.com/MrPlusGH/NPlusMiner/commit/105b19d4922e414aa79fde113c4443cf29965cc8

Thank you!
