### ISSUE TITLE
More equihash144 coins in Zergpool.com

### ISSUE THREAD

**Issue by nemosminer** [MrPlusGH/NPlusMiner#101]
https://github.com/nemosminer/NemosMiner/issues/716

**Comment by MrPlusGH** [comment]
Might not be that easy but if we were to implement some logic around option 3. I think it should do the trick.
ie: c=BTC,mc=Coin

1. Build some specific pool file (like ZergPoolCoins)
2. Get pool algo stats
3. Get pool coins stats
4. Generate pools for each coin (pass will be different "mc=" so each coin will be seen a different miner command)
5. Implement logic to change command line based on 'mc=' in miner file (Simple switch)
6. The current code should pick the coin with the highest price without requiring any change.

So for us that would be two things:
- addition of a specific pool
- modification of EWBFv2.ps1

For Pinpins: No change
 - @pinpins,
    - Note that is doesn't solve the issue for miners w/o profit switch
    - This will double API calls on each cycle

Thinking about it, we don't even need a specific pool file but can implement the logic in current Zergpool pool files. Like if equihash144 use option3.
It will make ZergPool different from others but I think this is manageable.

Thoughts?

**Comment by MrPlusGH** [comment]
Test branch: https://github.com/MrPlusGH/NPlusMiner/tree/BrainPlusTopCoin
