### ISSUE TITLE
Manual GPU selection issue

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner#102]
While using manual config, GPU selection is not properly handled and result in non expected GPUs to be selected.

**Comment by MrPlusGH** [comment]
Will be fixed in next version

**Comment by MrPlusGH** [comment]
Fixed in Master.
Opened for test. Please report if testing.

@jimmykl 
@NozMaximus
@spr32

**Comment by NozMaximus** [comment]
I can confidently say it is working now, and it keeps manually configured GPU selections.  Thank you again for the quick response and patch.

You need to make sure "ManualConfig" is set to true in the configuration file.  One of the miners caused the GUI to crash during benchmarking, but restarting everything seems to have resolved the issue.

Thanks

**Comment by MrPlusGH** [comment]
Thanks for reporting back!
