### ISSUE TITLE
Test ZergPoolPlusTopCoin

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner#104]
ZergPoolPlusTopCoin introduced as a new pool.
Available on master.

Note that is is in test. There is no guaranty on impacts on earnings.

ZergPoolPlusTopCoin combines BrainPlus calculations for ZergPool and find the best coin for the best algo.
Need to delete .\config\switching.log before first run

Anyone willing to test please report here

**Do not select multiple variants of the same pool.**

**Comment by ebojali** [comment]
I can test it for you but want some specifics on what feedback you want.. any specific logs etc?

**Comment by MrPlusGH** [comment]
Live test:
zergpoolplus : http://zergpool.com/?address=14rXrtks1c44az91FwDq6kuhM9U5WJqwj8

zerpoolpluscoins: http://zergpool.com/?address=1KqHHPLFsVZbPvDgP6CvcJ9uXiQoKL8iYj

**Comment by MrPlusGH** [comment]
@ebojali, Thanks for proposing help!
See my comments on your question #107 about test conditions and review https://github.com/nemosminer/NemosMiner/issues/716

**Comment by ebojali** [comment]
Sure I will take a look.. It seems plus functionality is outperforming pluscoins.can you do the same with normal vs plus as well? Is it is possible to run two instances of NplusMiner I can specify 3 GPUs for each and then compare it as you commented on my previous question

**Comment by MrPlusGH** [comment]
Yes, you can run multiple instances as long as they are in separated directories.
To select specific cards, you'll have to set ManualConfig to true in config.json and set selgpucc and selgpudtsm accordingly

**Comment by nemosminer** [comment]
hi MrPlus you happy with test can leave going longer if needed but zergpoolplus is consistently making  more than zergpoolpluscoins 

would you like me to switch test over to normal vs plus now?

i personally run 24hour on all my rigs so would like to test that against the winner of normal vs plus

**Comment by MrPlusGH** [comment]
Yeah you are right. I was kind of expecting this kind of results. It makes the switching rate higher and the miner warm up time is killing it. The pool does a much better job at directing hashrate to the best coin as it avoids this warm up time.

I'd say let's kill it for now and think about new improvements.

That is great learnings though. Thanks for the investiment in testing!

Super interested in side by side comparison of normal and plus. Let's do it.
In the normal vs Plus case, the test should be run longer (like 1 or two weeks) as we're kind of talking about market averages here. the advantage of Plus is in the long run.

MrPlus

**Comment by ebojali** [comment]
Cool.. keep up the great work guys!
Do you mind pasting the wallets that you use for the normal vs plus test?

**Comment by ebojali** [comment]
@MrPlusGH @nemosminer 

I've just initiated a test with plus functionality vs normal 3 1080 TIs in each: (in case you are interested to follow that) I will leave it up for approx 48h.

Plus enabled: http://zergpool.com/?address=16VewEctnWDCC5uBoB4Jt5PKJJ3m7y3Cbp
Notmal: http://zergpool.com/?address=1D3iiGVa9TzH8TAdLsvucZZT9mDCL7jQCc

Forgot to tell that it is testing towards a multi pool config consisting of ahash, zerg, zpool, nicehash

**Comment by ebojali** [comment]
@MrPlusGH @nemosminer 
With the above pools config, after 24h mining the summarized balance is recieved. I'll run it for 48h, but perhaps it is time to look through the plus functionality and how it performs.

Plus wallet: 0,00046786 BTC
Normal wallet: 0,00057165 BTC

**Comment by ebojali** [comment]
@MrPlusGH @nemosminer 

After 48h I have the following results
Plus wallet: 0,00090037
Normal wallet: 0,00108075

Clearly the plus functionality doesn't do what it is intended to do.. Any bugs?
