### ISSUE TITLE
Plus functionality vs normal?

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#107]
I find it really strange, you promote the plus functionality to be used but I average only 0.8 mBTC/day with that but when switching back to normal the GUI shows 2.6 mBTC/day. I have a 7 card 1080 Ti rig.. I really need you to explain how the plus functionality is supposed to give me more earnings? Perhaps earningstracker can somehow show me what is really earnt if I compare the two configurations(normal vs plus)? The version I use is 4.3

I would appreciate your input here.

**Comment by MrPlusGH** [comment]
Plus give more on the long run by minimizing switching rate and optimizing "time on Algo".
On short run, it might often be outperformed by Live. 

- Minimize switching
- Optimize "Time on Algo"
- Penalize or promote Algos on downtrend/uptrend (A hour variation from previous 24hrs)

EarningTracker does not do estimations but reports actual earnings. This is different from estimations (benchmark) used to take decisions.

How long have you been running your tests?
I'd say the bare minimum for a test is 12 hours and anything below 24 or 48 hours is meaningless.
Also, tests must run at the same time on equivalent hardware. If not, market fluctuations kills it.
See the kind of test and conditions we're running here: https://github.com/nemosminer/NemosMiner/issues/716 to validate hypothesis on future logic optimizations.

The below type of things clearly shows that depending on the time you look, you'll have a very different feeling (8 feels very good - 9 feels different)
![image](https://user-images.githubusercontent.com/36303784/42991528-25a936ba-8c06-11e8-81a8-ade49f9a4e8a.png)

I'm totaly opened to discussions to improve the logic. 

NPlusMiner keep the 3 options for pools so users can make their own choice. 
Happy to review tests results when they performed in the right conditions. This is how we learn and improve.

Let's discuss this further with more facts.
