### ISSUE TITLE
equihash144 on zergpool

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner#108]
@Pinpins shouldn't equihash144 be renamed on API to include coin name?

**Comment by pinpins** [comment]
Yes, I will do it, give me 24h. I will ping you once ready

**Comment by pinpins** [comment]
I got agreement with EWBF dev to get profit switch working without restart of miner. Going to test it in coming days, if works well, will announce instructions and lock coins under repsective equihash port. 

Until then will not change equihash144 to equihash144XSG, to prevent to frequent changes, and preferring to imeplement that one permanent..

**Comment by MrPlusGH** [comment]
Great!  Thanks for keeping us updated.
