### ISSUE TITLE
Default to all pool algo if algo list is blank

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner#109]
https://github.com/nemosminer/NemosMiner/issues/733

**Comment by MrPlusGH** [comment]
Done in Master

**Comment by MrPlusGH** [comment]
This will basically make the algo list dynamic based on what the pools are proposing as long as we have a miner for it.
I'm thinking of making this the default configuration.

This will play well with AutoUpdates as well

**Comment by scavern** [comment]
Testing has commenced! Maybe have a field where you can specify what algos you want to exclude?
