### ISSUE TITLE
CryptoDredge 0.6.0 crashes, upgrade to 0.7.0

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#111]
Cryptodredge 0.6.0 crashes on my rig from time to time running Lyra2RE2, but version 0.7.0 seems to be running fine. Please upgrade the ps1 file to download the 0.7.0 (https://github.com/technobyl/CryptoDredge/releases/download/v0.7.0/CryptoDredge_0.7.0_windows.zip)

**Comment by borzaka** [comment]
> [Lyra2REv2 Issues](https://github.com/technobyl/CryptoDredge#lyra2rev2-issues)
> In case if you have issues with the current implementation of Lyra2REv2 (lyra2v2), you might want to try lyra2v2-old.
> 
> CryptoDredge -a lyra2v2-old -o stratum+tcp://<POOL> -u <WALLET_ADDRESS>

**Comment by MrPlusGH** [comment]
Done
