### ISSUE TITLE
Benchmarking failed

### ISSUE THREAD

**Issue by JounouchiAng** [MrPlusGH/NPlusMiner#113]
This happened for latest master build.

https://imgur.com/a/AnQzq72

**Comment by MrPlusGH** [comment]
Which Pool?
I think BlazePool was having issues recently.

**Comment by JounouchiAng** [comment]
Hi Sir,

This is normal zergpool with LUX as password currency.

Not sure why the address is missing, I have checked the miner it is in the BIN folder.

**Comment by MrPlusGH** [comment]
Thanks for your help!
This is linked to an issue when the pool is not responding correctly.

Fixed in master
https://github.com/MrPlusGH/NPlusMiner/commit/5770d37381c89e770028d3b3750f02687024c1ae
