### ISSUE TITLE
Estimates incorrect for equihash on zergpool

### ISSUE THREAD

**Issue by scavern** [MrPlusGH/NPlusMiner#114]
or i would be a very very rich man by now...

![image](https://user-images.githubusercontent.com/13858299/43290227-beac16c6-912d-11e8-8dfd-aa6a82763d7d.png)

**Comment by scavern** [comment]
in retrospect i wonder if we should even bother... equihash mining on gpus are pretty much over!

**Comment by MrPlusGH** [comment]
switch your OS locale to US.

**Comment by scavern** [comment]
Why?


Do you know if something has changed at zergpool?


Interestingly yesterday it was only equihash at zergpool that was affected. Today it appears ALL the algo rates from zergpool are incorrect.


Zpool appears to be fine though (I only mine to these two pools).

________________________________
