### ISSUE TITLE
Plus functionality not working as intended.

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#116]
Please review the implementation of the plus functionality, clearly it is not working as intended.. See following thread for more information: https://github.com/MrPlusGH/NPlusMiner/issues/104

**Comment by MrPlusGH** [comment]
Thank you.
Give me some time to review this.
Though if you want to make a clear test you should make it on a single pool. If not you're dependant on other pools estimations.
What was your MinerGainPercent for the test?

**Comment by ebojali** [comment]
No worries just want to flag it for you guys. Why is a single pool more valid as a test than a multipool config? In my mind the same algo can pay more on different pools depending on the hashrate etc.. 

The MinerGainPercent is set to 8%.

**Comment by MrPlusGH** [comment]
Plus is definitely giving better earnings than live overtime for me.

**Comment by ebojali** [comment]
@MrPlusGH one last question. Did you test it in a single pool or multipool configuration?
