### ISSUE TITLE
T-Rex 0.5.5 new

### ISSUE THREAD

**Issue by jjziets** [MrPlusGH/NPlusMiner#117]
New algo x16s
Bug fixes:
Hung issue (after "ApiServer: stopped listening" and connection loss)
Immediate reconnect upon connection loss
Incorrect initialisation when invalid command line argument supplied (now the miner won't start in that case)

Linux
CUDA 9.1: 
https://mega.nz/#!ecVRWKZC!etz2LzGE5B8hn9oP2PoldJDAZIlV51NvAzDe8ayXdjM

CUDA 9.2:
https://mega.nz/#!PcMjDSDL!04CKqyBbxbu7VoT1__URl0Je9Z5Ms_mx2mtMCJzyDzY

Windows
CUDA 9.1/9.2:
https://mega.nz/#!HM1jgaCa!8OudAJG7HTXO8SwRzwKxwvK4cQhU4kPzxbE3IU_TXKY

**Comment by MrPlusGH** [comment]
Updated in Master
