### ISSUE TITLE
EWBF Cuda Equihash Miner v0.5

### ISSUE THREAD

**Issue by jjziets** [MrPlusGH/NPlusMiner#119]
v0.5
* 96_5 fixed the problem with cropped performance on fast (1080ti, Titan) gpu.
* 144_5 Speed up by 3-15% depends on the hardware.
* 210_9 Speed up by 2%.
* 210_9 Fixed "low difficulty shares" problem, on Aion pools. 
* 210_9 can now be used via --algo 210_9, I recommend using --algo aion for Aion mining, this will help you avoid problems with the wrong personalization string.
* Added option --intensity, this option will not increase performance, only slightly reduce the gpu usage, if you set it to 1. Works like --cuda_devices argument, 
   for example: --intensity 64 64 1 64 64 will apply the intensity 1 to the device with id 2.
 Special features (These features are added for specific projects,do not use these parameters on conventional pools):
* Added option --pers auto, Allow the pool to manage the personalization string. (Profit switching). (/http://zergpool.com)
* Added option --algo 144_5_EXCC_D For ExchangeCoin.

**Comment by jjziets** [comment]
https://bitcointalk.org/index.php?topic=4466962.0

**Comment by Olegik-ah** [comment]
zergpool changes:
https://bitcointalk.org/index.php?topic=2759935.msg43324268#msg43324268

**Comment by MrPlusGH** [comment]
Done on Master
