### ISSUE TITLE
Miner download/update bug

### ISSUE THREAD

**Issue by Olegik-ah** [MrPlusGH/NPlusMiner#120]
Hello!

For example. EVBF miner is running. I have changed download URI. In log i see:
Miner Updated: C:\Users\Administrator\Desktop\miners\NPlusMiner\Miners\EWBFv2.ps1
download is success. But update failed, because miner is running:
    + CategoryInfo          : PermissionDenied: (miner.exe:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Users\Administrator\Desktop\miners\NPlusMiner\Bin\NVIDIA-EWBFv2\: The process cannot
 access the file 'C:\Users\Administrator\Desktop\miners\NPlusMiner\Bin\NVIDIA-EWBFv2\' because it is being used by anoth
er process.
At C:\Users\Administrator\Desktop\miners\NPlusMiner\Core.ps1:232 char:61
+ ... iner.Path)) {Remove-Item -Force -Recurse (Split-Path $NewMiner.Path)}
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\Admini...\NVIDIA-EWBFv2\:DirectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand

But hash in config/MinersHash.json was changed.
As result i will never get updated miner.

Please, fix. Don't update miner hash if update failed.
Thanks!

**Comment by MrPlusGH** [comment]
Done in master.
If updated miner is currently running, it will be stop to allow update.

**Comment by Olegik-ah** [comment]
Thanks!
But something went wrong:(
Try:
1. Close NPlusMiner
2. Modify file in miners folder
3. Run NPlusMiner

Miner will not redownload and rebench will not start.

**Comment by Olegik-ah** [comment]
Also bug with this string:
Get-ChildItem -path ".\stats\" -filter "$($NewMiner.Name)_*.txt" | Remove-Item -Force -Recurse
Not working - stats files are not deleted during update...
