### ISSUE TITLE
Feature request: Autoupdate optionalminers if put in miners folder

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#122]
Hi,

I would request the autoupdate of optionalminers if the ps1 file has been moved into the miners folder. In my particular case I've moved trex.ps1 from optionalminers to miners folder. In 4.3.2 version it was using 0.5.1 and in the 4.4 release it is updated to 0.5.7. In order for the miner to get updated manual work is needed to move the ps1 file from optionalminers to miners folder. 

The improvement is to look if the old ps1 file is located in the miners folder and replace it in there directly, preferable a configurable variable "autoupdate optionalminers" tickbox in the GUI could be implemented controlling this.

Cheers!

**Comment by MrPlusGH** [comment]
Done in Master
https://github.com/MrPlusGH/NPlusMiner/commit/e3e807411a88c64bbf5a513ddda5e7ab16feac0e
