### ISSUE TITLE
Miner update/download bug

### ISSUE THREAD

**Issue by Olegik-ah** [MrPlusGH/NPlusMiner#127]
Hello!
1. Close NPlusMiner
2. Modify some file in Miner folder (new download path or change something in $Commands)
3. Start NPlusMiner

If you do it - NPlusMiner will not redownload miners on start... And also Stats will not dropped.

**Comment by MrPlusGH** [comment]
Just checked. It works.
It does take 3 NPlusMiner cycles so you might think its not picking it up at startup.
1 cycle - Starts normally
2 cycle - Detect change and download
3 cycle - Benchmark

**Comment by Olegik-ah** [comment]
I also checked it. Yes, it really takes 3 cycles. I thought that this should happen in 1 cycle.
But still there is a bug. As far as I understand - after downloading miner, the stats should be deleted. But it does not. After downloading the new version of the miner, the benchmark does not restart...
