### ISSUE TITLE
How to disable cryptodredge?

### ISSUE THREAD

**Issue by JoshDoesIT** [MrPlusGH/NPlusMiner#129]
I've never had luck with cryptodredge. It always fails, regardless of OC settings. The algs that are failing are lyra2v2 and phi2, both of which I'm pretty sure run fine using any other miner other than cryptodredge.

Is there any way to disable this miner without disabling the algs? Or, is there any particular reason you can think of as to why cryptodredge fails? It seems to start but then crashes.

**Comment by MrPlusGH** [comment]
Delete Cryptodredge.ps1 from your Miners folder.
