### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by gorsek1** [MrPlusGH/NPlusMiner#13]
Nplus miner just starts mining without benching first.

also when will you add Europe stratum support for zergpool?

thx bro

**Comment by MrPlusGH** [comment]
Is the Benchmark tab not saying benchmarking?
The main windows says mining even during benchmarks. But the Benchmark tab should tell which algo are being benchmarked.
I cannot reproduce this behavior. 
Could you confirm by looking at the Benchmark tab on a fresh start?

For zergpool EU servers, this is work in progress. #11

**Comment by gorsek1** [comment]
yeah sorry my mistake.
It was benching for 10mins 1 coins. and i tought that its just mining the 1st 1 on the list.
so in total it takes around 2 hours to bench em all.
