### ISSUE TITLE
manual Plus pool option configuration?

### ISSUE THREAD

**Issue by gak45** [MrPlusGH/NPlusMiner#130]
Any chance of offering a way to manually configure the timespan that Plus pools use for its decision making process? Optimally an extra box in the UI. But barring that what would I need to manually change in the files. 

I want to fine-tune it to make it 'better' for my mining needs as its default plus numbers... just dont work. Always lower avg than use realtime / older way... BUT I still want to remove the 'blips' that real-time pool option uses. EG sometimes HMQ1725/Lyra/Balloon gets hot. Sometimes its only a couple minutes long, others its 18hours. I want to minimize mining on the couple minute blips, but still get the longer ones. Right now the brain option waits way too long to switch over, and then stays too long once it cools down. Reducing profits to -at best- standard real-time pool option.

**Comment by MrPlusGH** [comment]
You can use BrainPlus.xml to configure BrainPlus options
