### ISSUE TITLE
Method invocation failed because...

### ISSUE THREAD

**Issue by spr32** [MrPlusGH/NPlusMiner#136]
Hi MrPlus!

I usually get this message on the console (4.6.0.1). Restart does not help.

Starting Cycle
Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
    + PSComputerName        : localhost

Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
    + PSComputerName        : localhost

Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
    + PSComputerName        : localhost

Loading BTC rate from 'api.coinbase.com'..
Loading pool stats..
Computing pool stats..

**Comment by MrPlusGH** [comment]
Could you try with 4.6.2 (just released)

**Comment by spr32** [comment]
Thanks, I'll try .

**Comment by MrPlusGH** [comment]
Any feedback?

**Comment by spr32** [comment]
So far, all works fine.

**Comment by MrPlusGH** [comment]
Thanks!
