### ISSUE TITLE
Lolminer for 1063

### ISSUE THREAD

**Issue by Yogurt79** [MrPlusGH/NPlusMiner#138]
Hi. How are you?
Please add LoLminer.
https://bitcointalk.org/index.php?topic=4724735.0
Thank you

**Comment by MrPlusGH** [comment]
Thanks.
Is it better than GMiner?
Do you have numbers?

**Comment by Yogurt79** [comment]
Win 10, Gminer does not work at 1063. Lolminer works
lolMiner Equihash Miner, Update: Jan 24th: lolMiner 0.7 alpha3 (Beam on 3G!)

**Comment by MrPlusGH** [comment]
Yep.
But we need to get card type detection in the product to select miner accordingly.
I'll see if I can get it as an optional miner in the meantime.

Low priority for now though...

**Comment by Yogurt79** [comment]
Let's take in the calculation of the card 1063 on win10. You will get your% and miners guys will be happy

**Comment by MrPlusGH** [comment]
I don't care about '%' :)
Just need bring users a reliable product that works.

If you dev, you can propose the miner file to be added to optional miners.

**Comment by Yogurt79** [comment]
https://github.com/Lolliedieb/lolMiner-preview/releases/tag/0.7_a3

**Comment by Yogurt79** [comment]
[lolMiner-preview-0.7_a3.zip](https://github.com/MrPlusGH/NPlusMiner/files/2818755/lolMiner-preview-0.7_a3.zip)

**Comment by Yogurt79** [comment]
[lolMiner-preview-0.7_a3.tar.gz](https://github.com/MrPlusGH/NPlusMiner/files/2818759/lolMiner-preview-0.7_a3.tar.gz)

**Comment by Yogurt79** [comment]
please

**Comment by MrPlusGH** [comment]
Hmm. 
Will wait for this one to be fixed...
https://github.com/Lolliedieb/lolMiner-preview/issues/18
