### ISSUE TITLE
bminer/gminer for grin29

### ISSUE THREAD

**Issue by Olegik-ah** [MrPlusGH/NPlusMiner#141]
Hi!
You have gminer and bminer for grin29. Gminer enabled by default.

But bminer have less fee and faster hashrate. In console they approx the same, but if i look at pool hashrate - bminer faster.

Rig 7x1070 on f2pool. Gminer(1.31) = 30-31g/s, Bminer(14.3) = 34-35g/s
Pls, check!

**Comment by MrPlusGH** [comment]
Here's what I'm getting testing on 1 single 1070.
Note that the 2% fee for GMiner is already taken out.

```
Miner              Algorithm            Speed mBTC/Day BTC/Day USD/Day   BTC/GH/Day Pool
-----              ---------            ----- -------- ------- -------   ---------- ----
GMiner             Beam            19.99  H/s    0.161 0.00016   0.573  8,037.96253 nicehash-
Bminer             Beam            17.48  H/s    0.141 0.00014   0.501  8,037.96253 nicehash-

**Comment by MrPlusGH** [comment]
Enable both for now.
NPlusMiner will select fastest depending on cards/rig perf
