### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by wxprofessor** [MrPlusGH/NPlusMiner#142]
Hello :)

Thank you so much for writing this wonderful application! After NiceHash V2 was discontinued, I simply could not get NHML to work on my box. Yours just works flawlessly! I've been mesmerized watching the miners do their thing. Just now this "booo" error started scrolling across the screen.. thought you should know! :)

![image](https://user-images.githubusercontent.com/5704029/53291479-f3acae80-3781-11e9-9d9b-7932ddd02704.png)

**Comment by MrPlusGH** [comment]
Thanks for the nice feedback!
Spread the word ;)

Could you let me know which algorithm and pool it was mining when it got these rejects?

**Comment by MrPlusGH** [comment]
@wxprofessor did you get your issue fixed?

**Comment by gak45** [comment]
Considering your dbag move to tell Nemos to stop using your code even though he kept all your copywrite notices AND was giving you 1/4 of his donations...AND yours was based off his to begin with I doubt you will get an answer. Only reason I am saying anything is this is my way of say buhbye. Never going to recommend your version to anyone again.
Good luck and I hope everyone else also blocks your greedy ass.

**Comment by MrPlusGH** [comment]
@gak45 
I fully understand people might have divergence of opinions.
I won't make noise with the reasons why Nemo and I ended up in that situation.
Your thoughts and choices are yours and I respect them.
Happy mining and hope to see you back.

+MrPlus
