### ISSUE TITLE
The UI freeze after pressing the start button.

### ISSUE THREAD

**Issue by spr32** [MrPlusGH/NPlusMiner#148]
Hi!

The UI freeze after pressing the start button. Default settings too.
Win10 X64 1903 , ver.: 5.0.1, 5.0.1.1

Thanks!

**Comment by MrPlusGH** [comment]
Will be fixed in next version.
5.1.0 is coming today.

Thanks for reporting here.

**Comment by MrPlusGH** [comment]
5.1.0 released
Setting this one as resolved

**Comment by spr32** [comment]
Doesn't work. :( 
My windows files is ok. (sfc /scannow ; DISM.exe /Online /Cleanup-image /Restorehealth)

**Comment by spr32** [comment]
The new update works! :)
Thank you MrPlus!

**Comment by Minerx117** [comment]
no worrys
