### ISSUE TITLE
12K Downloads! Thank you!

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner#150]
![image](https://user-images.githubusercontent.com/36303784/60755013-082f6c00-9fea-11e9-9a30-2dedebf4f4f7.png)

https://img.shields.io/github/downloads/mrplusgh/nplusminer/total.svghttps://img.shields.io/github/downloads/mrplusgh/nplusminer/total.svg

We just passed the 12K downloads bar :)

Thank you so much everyone!

**Comment by Minerx117** [comment]
Well Deserved MrPlusGH best of luck for the future
Best Regards
Nemo

**Comment by MrPlusGH** [comment]
Thanks Nemo @nemosminer @Minerx117 
Unfortunate split we have right now. Let it be that way at this time.
Might collaborate again one day.
