### ISSUE TITLE
Proud and happy. Thank you Zergpool.

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner#152]
We feel proud and happy that NPlusMiner landed on ZergPool front page today.
Many thanks to ZergPool OPs team for their demonstrated trust!

![image](https://user-images.githubusercontent.com/36303784/60811281-369a7c00-a18f-11e9-9552-4ea09856cba4.png)

MrPlus

**Comment by Minerx117** [comment]
Congratulations @MrPlusGH
