### ISSUE TITLE
 linux HiveOS version

### ISSUE THREAD

**Issue by 0398955** [MrPlusGH/NPlusMiner#154]
When will the linux HiveOS version be available?

**Comment by MrPlusGH** [comment]
Could you expand on the value this would bring?

**Comment by 0398955** [comment]
HiveOS, at the moment, is the most stable linux system. Not requiring a large number of system resources, unlike WindowsOS. Take for example a very large swap file in MSOS.

**Comment by MrPlusGH** [comment]
No plan for it yet.
