### ISSUE TITLE
ccminerAlexis78 uses wrong parameter for polytimos

### ISSUE THREAD

**Issue by grantemsley** [MrPlusGH/NPlusMiner#156]
Miner fails to benchmark because it's using "-a Polytimos" but the miner expects "-a poly".

**Comment by MrPlusGH** [comment]
Thanks for reporting !
Fixed here: https://github.com/MrPlusGH/NPlusMiner/commit/178839a3fc114caf9f8b9b371078339427f8594b

Actually helped fixed another issue: https://github.com/MrPlusGH/NPlusMiner/commit/5fa7d8ef276da22d6f8fb79e581eced53980a80e
