### ISSUE TITLE
Strange with CPU algo

### ISSUE THREAD

**Issue by Olegik-ah** [MrPlusGH/NPlusMiner#159]
Hi!

Something strange with CPU algo. CryptonightV7 algo Enabled, XMRig (cpu) enabled, but XMRig with CryptonightV7 not showing in CPU miners section.
![2019-12-06_12-09-48](https://user-images.githubusercontent.com/31293967/70311008-dda84000-1821-11ea-894c-aeadfe59dc85.png)

**Comment by MrPlusGH** [comment]
Thanks for reporting. Fixed and will be next version.
https://github.com/MrPlusGH/NPlusMiner/commit/653e044ecb9c3148dff768c63bd703a841a071a1

in the meantime, you could unselect ShowOnlyTopCoins in config to shall all.

**Comment by Olegik-ah** [comment]
Thanks! I'll try when it will be released.

**Comment by MrPlusGH** [comment]
Released
