### ISSUE TITLE
c11 zergpool.com problem

### ISSUE THREAD

**Issue by tiotoi** [MrPlusGH/NPlusMiner#16]
Hi MrPlus, i have an issue with c11 algo on zergpool.com sometimes. Is that possible that pool not accepting this algo during technical work or another reason.
Please see below:

<img width="1137" alt="screen shot 2018-03-10 at 9 51 08 am" src="https://user-images.githubusercontent.com/9711334/37243537-1af8e15e-2449-11e8-856b-b18132cbf4dd.png">
and few min after.....
<img width="1032" alt="screen shot 2018-03-10 at 9 55 53 am" src="https://user-images.githubusercontent.com/9711334/37243545-4e8db7ec-2449-11e8-85d0-8b8255071ce1.png">

**Comment by MrPlusGH** [comment]
That's a pool connectivity issue. Looks like the Pool was down at this time. (or network.)

**Comment by tiotoi** [comment]
Thanks a lot MrPlus. One more question, i realize sometimes it stoped to work coz c11 algo (win 10 blue screen) any idea?
Im not overclocking GPU's 
<img width="631" alt="screen shot 2018-03-10 at 10 29 43 am" src="https://user-images.githubusercontent.com/9711334/37243843-0729b8ec-244e-11e8-82a4-a759ad4b1b57.png">

**Comment by MrPlusGH** [comment]
This is not c11, ccminer-x64 is only used for x16r and lyra2z.
Try lowering the intensity on these algo.

**Comment by tiotoi** [comment]
-i 19 or i 21.5?

"x16r" = " -i 21.5 $SelGPUCC --api-remote --api-allow=0/0" #X16r
or
"x16r" = " -d -i 21.5 $SelGPUCC --api-remote --api-allow=0/0" #X16r

**Comment by MrPlusGH** [comment]
"x16r" = " -i xx -d $SelGPUCC --api-remote --api-allow=0/0" #X16r

**Comment by tiotoi** [comment]
you are the Best!
thanks a lot!
