### ISSUE TITLE
Plz, fix format errors

### ISSUE THREAD

**Issue by Olegik-ah** [MrPlusGH/NPlusMiner#160]
All details on the picture. First rig on Russian OS, second on Eng OS. Fix, please
![image](https://user-images.githubusercontent.com/31293967/70339086-3a761b80-185f-11ea-8c05-2970f67c2666.png)

**Comment by MrPlusGH** [comment]
Hi, could you share logs\dailyearnings.csv?

**Comment by MrPlusGH** [comment]
Never-mind. Fixed ;)
https://github.com/MrPlusGH/NPlusMiner/commit/c5dc973b35ca66fbdee7a9b34c77e8bf34e42d33
Will be in next version. Thank you !

**Comment by Olegik-ah** [comment]
Thanks! I'll try when it will be released.

**Comment by MrPlusGH** [comment]
Released
