### ISSUE TITLE
CPU-JayDDee fails to run using Argon2dDyn algorithm parameter

### ISSUE THREAD

**Issue by syl3ntz** [MrPlusGH/NPlusMiner#161]
Error:  Unknown algo:  Argon2dDyn - in miner window using NPlus 6.0.5 generated parameters.
Include.ps1:1161 - Get-Algorithm sets:  "argon2DYN":  "Argon2dDYN" using .\Includes\Algorithms.txt which CPU-JayDDee is unaware of.  Using --help it appears the argon2d-dyn should be using "-a argon2d500"

**Comment by syl3ntz** [comment]
![](https://cdn.discordapp.com/attachments/527915837806608398/652633074336661539/unknown.png)

**Comment by syl3ntz** [comment]
![](https://cdn.discordapp.com/attachments/527915837806608398/652633448535687168/unknown.png)

**Comment by MrPlusGH** [comment]
Fixed algo.
Disabled algo as no profit on CPU anyway.
https://github.com/MrPlusGH/NPlusMiner/commit/bf3405641e726e6f9aa204ea92443940efd14db2

Will be in next version
Thank you!
