### ISSUE TITLE
Simple question confirmation please

### ISSUE THREAD

**Issue by imrecsoka** [MrPlusGH/NPlusMiner#165]
Just want to confirm the meaning of this message ?  : 
"The update file below is only here to serve AutoUpdates. **_Do not download_** !"

![image](https://user-images.githubusercontent.com/25494601/74100090-e3920880-4b65-11ea-9357-521c7665e94f.png)

I am trying to make sense of this. I downloaded NPlusMiner-6.1.10.zip and then do i just go ahead and run the NPlusMiner shortcut ?

If i want to, then do i download the Update-6.1.10.zip file:  (optional ?)

Do I need to extract and over write the files i have already extracted from NPlusMiner-6.1.10.zip ?

Thank you
Regards

**Comment by MrPlusGH** [comment]
Hi,

You just need to download NPlusMiner-6.1.10.zip and run the shortcut.
NPlusMiner has an autoupdate features which will pick up the update and apply it automatically when we release the next version.
