### ISSUE TITLE
Conflict With AMD and NVIDIA

### ISSUE THREAD

**Issue by jgonzi** [MrPlusGH/NPlusMiner#166]
Hi,

I suppose it is not normal, but if you have 2 Cards, 1 AMD and 1 NVIDIA, the t-rex ist not working for the parameter: -d 0,1

In the Config we should be able to put this paramert or at least edit a cfg file to do it manually.

One of the displays is not allowed. In my case 0 was Nvidia and 1 AMD... 

Also this line return : wildrig.exe  --api-port=4068 --url=blake2b.mine.zergpool.com:5777 --opencl-threads auto --opencl-launch auto --user= xxx --pass=ID=xxxxx,c=LTC,m=party.NPlusMiner,mc=TNET --algo blake2b

blake2b is not supported. 

Many thanks for all your help

**Comment by jgonzi** [comment]
I saw another conflict.... with Gminer:

.\Bin\NVIDIA-Gminer\miner.exe  --devices 0 -t 95 --watchdog 0 --api 4069 ....

Error: "Failed to initialize miner on GPU0: MSI Radeon RX 560 Series 4GB: Device not supported for this algorithm No devices for mining" 

And I have only minned for NVIDIA

**Comment by MrPlusGH** [comment]
Hello,
Mixed rigs are not supported (AMD/NVIDIA)
