### ISSUE TITLE
1.7.4 - First time user

### ISSUE THREAD

**Issue by imrecsoka** [MrPlusGH/NPlusMiner#169]
1.7.4 - First time user:

I will have a look at the GUI and see how it works for me.
No offense i tried Megaminer and Mining Pool Hub by Aaron - good but no longer deved.
I tried Rainbow miner , so bloody complicated, I managed to get API keys and blood type and stuff but its ridiculous to be setting up so many items.
I will see how NPlusMiner serves me.

Update :
Ive noticed Phoenix miner is not being used - i have an AMD GPU
Ive also noticed Claymore dual miner is not being used

**Comment by MrPlusGH** [comment]
Welcome. 
NPlusMiner is built to be way simpler than the tools you mentioned. 
We value any type of constructive feedback so don't hesitate. Here or on our Discord.

**Comment by imrecsoka** [comment]
Hi, okay , so very sad Phoenix nor Claymore is being used for AMD.
I do currently mine Ethereum and they do work
Unsure about the custom miner part as i would like mainly all to be automatic as Megaminer or MiningPoolMiner was - i entered in my bitcoin adrress and that was it.
Agree that the Rainbowminer is more complicated definitely not user friendly.
Although not profitable now, Pascal Coin and Digibyte (skein on AMD ) might be worth looking in to.
The correct varient of  CGMiner or SGMiner will work for Skein AMD.
We have to consider x16rv2 and kowpow - example Ravencoin
Let me know what you think, thanks.
