### ISSUE TITLE
DSTM miner / Equihash / Stratum is empty

### ISSUE THREAD

**Issue by tiotoi** [MrPlusGH/NPlusMiner#17]
Hi guys,
is anybodies has the problem with with Equihash? 
Stratum is blank.
<img width="767" alt="screen shot 2018-03-10 at 12 25 25 pm" src="https://user-images.githubusercontent.com/9711334/37244916-5356f896-245e-11e8-8e1c-897cd53838c3.png">

**Comment by MrPlusGH** [comment]
Do you happen to know which pool it was trying to mine at that time?

**Comment by tiotoi** [comment]
No, don’t have any idea. i'll keep my eye out.

**Comment by MrPlusGH** [comment]
You could find out in miner.log
Would help if you could post corresponding entries

**Comment by MrPlusGH** [comment]
Fixed in 2.1
