### ISSUE TITLE
Some dependencies are missing. Installing.

### ISSUE THREAD

**Issue by ZeddieXX** [MrPlusGH/NPlusMiner#171]
After running NPlusMiner a few times already, it would still say "Some dependencies are missing. Installing." and prompting a UAC challenge dialog box.

I thought by now all dependencies are installed because no miners are failing.  This is causing a problem when if I ever reboot my machine and automatically starts NPlusMiner because it just hangs at the UAC challenge dialog box.

**Comment by MrPlusGH** [comment]
A few users have reported this issue.
We are failing to repro so difficult to fix. We are still investigating.

solution is to run the prereqs install script as admin manually. (You just need to do this once)

- Open powershell as admin
- Switch to the NPlusMiner root directory
  - cd c:\xxx\xxxx\NPlusMiner
- Run the following
  - ```Set-ExecutionPolicy Unrestricted ; .\Utils\InstallPreReqs.ps1 ; Set-ExecutionPolicy Restricted```
  - Answer Yes when asked
