### ISSUE TITLE
NiceHash poolbalance values are incorrect

### ISSUE THREAD

**Issue by UselessGuru** [MrPlusGH/NPlusMiner#172]
The unpaidAmount in https://github.com/MrPlusGH/NPlusMiner/blob/fd80253ad25f5e62d3d3bf12ab22c161bf5e6110/Includes/EarningsTracker.ps1#L118
gets reset every 4hrs.
-> Data is only correct for the first 4hrs per day 👎

**Comment by MrPlusGH** [comment]
`[Double]$NHTotalBalance = [Double]($TempBalanceData.unpaidAmount) + [Double]($TempBalanceData.externalBalance)`

That is why we're adding up externalBalance to get the full value. Problem is that the NiceHash API does not always set both values accordingly in time. So the 1hr value might be wrong at the time of reset. But it corrects itself after 1 hour and the 6hr and 24hr values are still correct.
