### ISSUE TITLE
Any thoughts on making a Linux version?

### ISSUE THREAD

**Issue by ZeddieXX** [MrPlusGH/NPlusMiner#174]
I love this project so far.  However, I've been trying to move away from Windows for a while.  I use this on my main PC with SLI graphics and only mine when I'm not actively using it.

Is it feasible to to make a version for Linux?  I know there are miner binaries for Linux, but not sure how the scripting would translate, as well a how to control the underclocking/volting with the GPUs in Linux.

I searched and haven't found anything like this for Linux.

**Comment by MrPlusGH** [comment]
We have no short term plans for a Linux version.
Might come later
