### ISSUE TITLE
Argon2dCrds

### ISSUE THREAD

**Issue by ZeddieXX** [MrPlusGH/NPlusMiner#176]
`.\Bin\CPU-JayDDee\cpuminer-aes-sse42.exe --cpu-affinity AAAA -q -t 6 -b 4068 -a Argon2dCrds -o stratum+tcp://argon2d250.na.mine.zpool.ca:4238 -u xxxxx-p ID=c=BTC,zap=ZMY`

This is failing.  I think it's because the "-a Argon2dCrds" should be "-a argon2d250".

If you do a "--help", it does not list "Argon2dCrds" as a valid algorithm.

**Comment by MrPlusGH** [comment]
Should be fixed in master
