### ISSUE TITLE
Suggestions for tracking

### ISSUE THREAD

**Issue by airwalker1** [MrPlusGH/NPlusMiner#18]
I absolutely love the tracking stats! Thank you. Could you please implement the following:

1.) Ability to track multiple pools at the same time under one batch file just as when using multiple pools for mining in one start batch.

2.) Calculate based on total unpaid vs. balance. It can take alot of time to clear pending, this way you can see up front.

**Comment by MrPlusGH** [comment]
Tracking uses total_earned when available on pool (ahashpool) or Total when not (other pools).
And then compare to balance for payment estimate.
Total_earned and Total include it all so that is the most accurate.
