### ISSUE TITLE
7.7.0 sur Lyra2v3 Nvidia 1 seul GPU utilisé

### ISSUE THREAD

**Issue by P-tite-tete** [MrPlusGH/NPlusMiner#183]
Bonjour je viens de mettre en place la version 7.7.0 et lors de lancement en Nvidia du Lyra2v3 un seul de mes GPU est utilisé.
Est-ce normal ou il y at'il un bug?

![image](https://user-images.githubusercontent.com/5289783/106902649-5c845b80-66f9-11eb-9117-253654d528f3.png)
![image](https://user-images.githubusercontent.com/5289783/106902699-68701d80-66f9-11eb-954b-eb187d81cd6f.png)
![image](https://user-images.githubusercontent.com/5289783/106902732-6e65fe80-66f9-11eb-80bb-983ff7efcabe.png)

**Comment by P-tite-tete** [comment]
[miner-20210204.log](https://github.com/MrPlusGH/NPlusMiner/files/5926181/miner-20210204.log)
[ServerTR.log](https://github.com/MrPlusGH/NPlusMiner/files/5926182/ServerTR.log)
[switching.log](https://github.com/MrPlusGH/NPlusMiner/files/5926183/switching.log)
J'avais oublier les fichiers de logs

**Comment by MrPlusGH** [comment]
Sorry. But could you please translate to English?

**Comment by MrPlusGH** [comment]
This a miner limitation. 
CCMiner lyra2z330 will be used after benchmark
