### ISSUE TITLE
Unresponsive GUI

### ISSUE THREAD

**Issue by MitchCarroll** [MrPlusGH/NPlusMiner#184]
Since the last few updates, sometimes the GUI will become unresponsive when running. The startup time seems to have increased drastically, and the stop/shutdown time even more so. The GUI seems to be taking up almost 100% of the CPU, so that when a CPU miner is running, when lines of text would normally be printed out fast enough that it's hard to read them before they scroll by, now they print out one character at a time, with a second or so between characters. Sometimes the GPU miners do this too. This happens even after a clean reboot on a 9th gen i7 with a GeForce RTX 2060. Often, after starting mining, even a few hours later the GUI will report a hashrate of 0, even if the miners report otherwise, and sometimes, it will even tell me that the miners are stopped when I can clearly see them working. Killing the GUI doesn't always seem to release resources either.

**Comment by MrPlusGH** [comment]
This might happen when mining heavy algos on CPU.
RadomWOW being one.
You could exclude these heavy algos in config.
