### ISSUE TITLE
Verthash miner fails with space in path

### ISSUE THREAD

**Issue by johnrando** [MrPlusGH/NPlusMiner#185]
edit: this is with NPlusMiner 7.8.1.  I see a note in 7.6.5 related to space in Verthash path, not sure if this was a regression or if it wasn't fully fixed then.

Miner log shows:

`.\Bin\NVIDIA-VertHash\VerthashMiner.exe  -o stratum+tcp://verthash.na.mine.zergpool.com:4534 -a Verthash -u WALLET -p ID=minerID,c=BTC,mc=VTC -D 0 --verthash-data "C:\Users\Name`

for my setup, verthash-data path should be "C:\Users\Name Goes Here\Desktop\NPlusMiner\Bin\NVIDIA-Verthash\verthash.dat"

This change to Line 6 of Verthash.ps1 seems to fix the issue for me:

`$DatPath = ".\Bin\NVIDIA-VertHash\Verthash.dat"`

**Comment by MrPlusGH** [comment]
Thanks!

Will be in next version.
