### ISSUE TITLE
main window update

### ISSUE THREAD

**Issue by szentigrad3** [MrPlusGH/NPlusMiner#186]
i would like to see in the main window an update to show the coin you are mining instead of always BTC
![dBZ6QHK](https://user-images.githubusercontent.com/5462780/110885968-ebf5dd80-833b-11eb-8c26-c5f12c4ebfd6.png)

**Comment by MrPlusGH** [comment]
Earnings tracker shows selected payout currency but we do keep BTC as a reference for profitability comparisons.
This is by design.
