### ISSUE TITLE
mbtc/gh/day values not updating

### ISSUE THREAD

**Issue by geckah** [MrPlusGH/NPlusMiner#22]
using the master copy and the values are not changing even after 12 hours. Is this supposed to happen?

**Comment by MrPlusGH** [comment]
which pool are you using?
When did you get the version?
this has changed yesterday:

Plus logic fixes
    Implemented web request caching bypass so data refreshes correctly. (Thanks GraySergey and dwellhurtyswan)

**Comment by geckah** [comment]
Got it a couple of days ago. Downloaded the master copy earlier today and everything works.
