### ISSUE TITLE
Help and howtos

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner#23]

**Comment by tiotoi** [comment]
What king of help do you exactly need?

**Comment by MrPlusGH** [comment]
Would like to create nice help and howtos for specific advanced config like per pool config, multi instances and so on.
This to make people life easy.
But I can't find the time to make it happen.

**Comment by monkeyguy** [comment]
Would love to help, not a programmer, but have definitely done my fair share of fiddling with configs and tweaking stuff. LMK what I can do.

**Comment by MrPlusGH** [comment]
Let's may be try it this way...
I created a repository called NPlusMiner-Documentation and invited you @monkeyguy as a collaborator to it. (also invited @Tesla74 as he said he might wanna help)

I believe that it means you have edit permissions on the Wiki in this repository so that should work.
We could then have a couple wiki pages to help users?

Not sure that's the best way to proceed, let's try and discuss

**Comment by monkeyguy** [comment]
Seems like a good way to do it imo. Like I said, I'm no programmer, but I would be happy to help. Could you suggest a specific process you think might need some clarification? I'll whip up a draft step-by-step sort of thing for it and you could give me feedback on the good and bad of what I come up with.

**Comment by Tesla74** [comment]
Thanks MrPlus.  Where do I go to accept invite?  I don't have write access.

**Comment by MrPlusGH** [comment]
Not sure... Here's the invite link for Tesla74: https://github.com/MrPlusGH/NPlusMiner-Documentation/invitations

**Comment by Tesla74** [comment]
That worked.. Thanks

**Comment by MrPlusGH** [comment]
Great that it works!
For @monkeyguy : https://github.com/MrPlusGH/NPlusMiner-Documentation/invitations

**Comment by MrPlusGH** [comment]
@monkeyguy @Tesla74 are you guys able to update the wiki?

**Comment by Tesla74** [comment]
Yes, I am able to edit the wiki.  I've uploaded a write up on overclocking.  Edit anything you see that should be changed.  If all looks good, I'll add to the wiki.

Does NvidiaInspector override any running overclocking software?

**Comment by monkeyguy** [comment]
I accepted the invite and it looks like I can edit now

**Comment by MrPlusGH** [comment]
Thank you @Tesla74 !
Tracking it here: https://github.com/MrPlusGH/NPlusMiner-Documentation/issues/1
