### ISSUE TITLE
Released 2.0.3

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner#27]
Released 2.0.3

- GPU count detection
    - NPlusMiner will detect GPU count at start if not set in config
- Disable GPU0 option
    - Ability to use all GPU but 0 per our users request
- "-Config" at launch
    - Allows to run with different prepared configurations
    - To use different config files. NPlusMiner can be launched with -config <ConfigFilePath>
    - See example in "NPlusMiner With ConfigFile.bat"
- BTC Price information added
- Added NPlusMiner-ConsoleUp for console lovers
    - Use this to launch the Application with the Console UI
- Fixed error raised after miners download
- Renamed "\prerun\default.bat" to "default-Example.bat" to avoid launching an empty bat if prerun is not used

**Comment by RobinMM** [comment]
![image](https://user-images.githubusercontent.com/1236301/37344799-a57d55ce-26cb-11e8-88af-bc579d635dce.png)
There is a small issue with BTC price info, its showing bitcoin value in dollar not in euro, is there any way to edit this?

**Comment by MrPlusGH** [comment]
Thanks you!
Fixed in dev. Not yet on GitHub. Will be fixed in next version.

**Comment by RobinMM** [comment]
No problem! looking forward to your next release :) keep up to good work!
