### ISSUE TITLE
Miner Enemy-Miner

### ISSUE THREAD

**Issue by jcabello7** [MrPlusGH/NPlusMiner#28]
Ei man! Great work with Nplus Miner.
Maybe you could use EnemyMiner for X16r and X17?

https://gyazo.com/9fa19f8be0bb9d010df14b66c4c05997

Thanks for your work!!!

**Comment by nemosminer** [comment]
if only there was a source code...... https://github.com/nemosminer/NemosMiner-v2.5.2-windows/issues/375

**Comment by MrPlusGH** [comment]
If only...
