### ISSUE TITLE
Currency, EUR - USD

### ISSUE THREAD

**Issue by uprise88** [MrPlusGH/NPlusMiner#30]
Hi there, selecting EUR currency instead of USD but console still shows USD

**Comment by MrPlusGH** [comment]
Thank you. Will look at it.
In the mean time. That works well in the GUI.

**Comment by MrPlusGH** [comment]
Fixed in 2.1.1

**Comment by uprise88** [comment]
Im sorry to pester but its not working, and i have another problem too.. when using LTC passwordcurrency it sends out c=BTC intsead of LTC...

<a href="https://ibb.co/nA3HSx"><img src="https://thumb.ibb.co/nA3HSx/Immagine.jpg" alt="Immagine" border="0"></a>

**Comment by MrPlusGH** [comment]
Sorry, only fixed the top ticker :(
Will be fixed in next version.
