### ISSUE TITLE
Running multiple instances - Port detection timing

### ISSUE THREAD

**Issue by Olegik-ah** [MrPlusGH/NPlusMiner#31]
Hi!
Sorry for my bad english...
I think you have choose wrong way to allocate free TCP port for miner APIs...  For example - i have 2 instances of nplusminer on my rig. Both of them want to switch miner in 1 time. But first instance wants to switch to X17 algo, second to Lyra2v2. Both miners calls "Get-FreeTcpPort" and recieves 4068 port. As a result - we can have corrupted Stats in one instance and failed miner on second instance.
I think - you should add 1 config param - "instance number" and allocate different port ranges... For example: 4068 + 20*instance number.
Thanks for your work!

**Comment by Olegik-ah** [comment]
I see, that Nemo have same code... But i think it is your code and implementation:) Thats why i write here

**Comment by MrPlusGH** [comment]
Yes, we share the same code.

Get-FreeTcpPort is called only once at start, not when miners are launched. That is why the readme says that miners of the first instance must be running prior starting the second instance.
Make sure first instance mines before starting the second and you should be fine.

If you automatically start NPlusMiner instances on windows startup, get a one minute sleep in the second instance batch.

I agree it might not be the best but this avoids polling port on every switch. (Polling ports too often might make some AV not happy)
I might review this later.

Your suggestion of adding 4068+[InstanceID] won't work if the port is used by any other app.

**Comment by MrPlusGH** [comment]
Quickly made this for you on a separate branch.
It will check available ports at each miner launch.
Let me know how it goes.
[https://github.com/MrPlusGH/NPlusMiner/archive/PortDetectAtMinerLaunch.zip](url)

**Comment by Olegik-ah** [comment]
Thanks for your reply.
My suggestion is:
Function Get-FreeTcpPort {
	$StartPort = 4068 + **[InstanceID] * 10**
	$PortFound = $false
	$Port = $StartPort
	While ($Port -le ($StartPort + **9**) -and !$PortFound) {try{$Null = New-Object System.Net.Sockets.TCPClient -ArgumentList 127.0.0.1,$Port;$Port++} catch {$Port;$PortFound=$True}}
}
Or you can use first GPU number from config instead of InstanceID (1st instance GPU 0,1,2 second GPU 3,4,5)

**Comment by Olegik-ah** [comment]
I'm programmer too. But i dont know PS syntax. My languages c++, c#, vb.net

**Comment by MrPlusGH** [comment]
What i don't see is what it changes from what's done currently?
This would just change the port range.

**Comment by Olegik-ah** [comment]
> This would just change the port range.

For different instances

**Comment by MrPlusGH** [comment]
Have you had a change to test the proposed version?

**Comment by Olegik-ah** [comment]
Hello!
Yes, no bugs yet. I have read your code and understand that it was my fail...
But i still have a trouble with stats updating. Now i'm trying zergpool. Pinpin now having trouble with ddos protections and miners some time losing connection... It doesn't matter witch pool i use - same issue can happen if internet connection is down for a while.
For example i have 1 1060 card and real hashrate on skein about 320Mh/s. When miner is running more than  [StatsInterval] your miner start to update Stats... If during the [StatsInterval] miner software have lose connection - it reports incorrect avr speed via API. Maybe you can make some mods to Stats updating procedure? For example - if current speed more than 20% less, than the Live/Minute/5minute from stats - dont update stats speed.
Thanks a lot!

**Comment by MrPlusGH** [comment]
Thanks for testing. Will include the change in next version.

**Comment by MrPlusGH** [comment]
If found case where miner don't like the port poll and stop :(
Need further investigations. Might be better way to detect available ports.
Sticking to detection at start for now.
