### ISSUE TITLE
NVidia settings question

### ISSUE THREAD

**Issue by PRoGoNdo** [MrPlusGH/NPlusMiner#32]
I'm very new to all this. Somewhere i read that setting "Optimize for compute performance" to "ON' under the Nvidia control panel would help? When I do then start Nplusminer the console tells me all Cuda cores are in use  in red and nothing gets mined. Should I just leave it off since it mines just fine with it off? BTW im using a gtx 970  (soon to be 2 1080ti i hope)

Thanks for any help someone can give me. Sorry if its a stupid question. Any help would be appreciated

**Comment by nemosminer** [comment]
with intensity setting we use i don't think a 970 will work (atm we configured for 10603gb to 1080ti) 

the lowest card that is tested is 10603gb... i have tested with 1050ti and it fails on some miners... 

Nvidia posted a KB article to help with the explanation:
It's a setting for second generation Maxwell cards to improve their non-gaming compute performance.
no longer exist in the 10 series cards...

you can try with leaving Optimize for compute performance off see if it helps...

get the 2x1080ti's sell the 970 : )
