### ISSUE TITLE
No miners - files missing?

### ISSUE THREAD

**Issue by PRoGoNdo** [MrPlusGH/NPlusMiner#33]
Also im getting this in 2.1.1

GPU #0: Cuda error in func 'neoscrypt_cpu_init_2stream' at line 1445 : out of memory.
[2018-03-17 08:01:25] stopping 1 threads

reinstalled (new unzipped 2.1.1 clicked start mining and i get this error and it stops there. (yes optimize for compute performance is off). I do not get this error in 2.1 What am I doing wrong? Yes i have tried google but there is just so much out there that i cant find a clear answer as to what to do. thank you again 

EDIT: going back to 2.1 I now get a spam of red text in console and it dies too. I think problem started after I overclocked my gpu a bit to high but still the same issue even after i set all oc setting back to factory. Im having NO issues on games or any regular use with my card.
[console spam that it shows'.txt](https://github.com/MrPlusGH/NPlusMiner/files/1821630/console.spam.that.it.shows.txt)

**Comment by MrPlusGH** [comment]
Looks like some files are missing...
Do you see exe files under the respective directories in \miners?
Do you have an AV installed which could have quarantined the files?

**Comment by PRoGoNdo** [comment]
I seemed to have fixed this issue by clean installing my newest Nvidia driver and redownloading and extracting  Nplusminer then running it. on bot 2.1 and 2.1.1. I do use the microsoft defender but its been on since i started this who mining this and its been fine. either way fixed the issue, something got curropted when i pushed msi afterburner too high. thanks for your reply :-)
