### ISSUE TITLE
RavenMiner 1080TI issues

### ISSUE THREAD

**Issue by jcabello7** [MrPlusGH/NPlusMiner#34]
Hi!
I see that my rigs with 1080TIs are crashing a lot when mining X16R.
GPU usage is very unstable and with a lot of spykes.
I must underclock all GPUs to avoid crashes.
https://gyazo.com/9038dd8f3a7f39f133493c64a7fe6ac2
What could we do?
Note: My 980TIs rig is working OK. Issues only with 1080TI.

**Comment by MrPlusGH** [comment]
You could use the prerun feature to set a specific OC for x16r using nvidiainspector, you'll just need a default.bat with your wanted default OC settings and a x16r.bat with the specific settings for that algo.

X16r uses a combination of a lot of other algos which makes it a bit tricky..

**Comment by tiotoi** [comment]
hi @MrPlusGH , i have a same problem....
could you please share an example of x16r.bat with a default settings?

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/issues/375

**Comment by MrPlusGH** [comment]
There is one in the default-EXAMPLE.bat file

Use OC with caution!
This is just an example. I'm not responsible of any result this might bring.
