### ISSUE TITLE
excavator

### ISSUE THREAD

**Issue by gak45** [MrPlusGH/NPlusMiner#35]
Any chance of doing some excavator miner files for Nplus? SniffDog gets around the EULA by #'ing out all alogs and making peeps manually modd the file for it to work. MPM makes you DL manually. Either would be awesome as Neoscrypt is faster with excavator!

**Comment by nemosminer** [comment]
gak45 we should be able to make it work

**Comment by MrPlusGH** [comment]
@nemosminer,  I have an idea on this one (and other ""custom"" miners files.
Let's discuss after the next release.

**Comment by Tesla74** [comment]
Having script, but require manually download should be fine.

**Comment by gak45** [comment]
Thanks!

**Comment by MrPlusGH** [comment]
Have a look at the Optional Miners thing in 2.1.2...
