### ISSUE TITLE
HiveOS compatibility?

### ISSUE THREAD

**Issue by tiotoi** [MrPlusGH/NPlusMiner#36]
Hi @MrPlusGH , is there any think to make it works with HiveOS?

**Comment by nemosminer** [comment]
have you tried : https://github.com/nemosminer/NemosMiner-v2.5.2-linux-HIVE-OS still work in progress i haven't tested myself 

if you get into work let us know  
also you can try : https://github.com/nemosminer/NemosMiner/archive/linux.zip

**Comment by tiotoi** [comment]
@nemosminer thanks a lot. ill try to install it immediately
let you know after

**Comment by tiotoi** [comment]
@nemosminer if i understood well, to run this is have to install these on two different cumputers?!
install nemosminer on windows and *py files on hiveos? is thats right?

**Comment by nemosminer** [comment]
to be honest i have not looked into it yet as  all time has gone into the windows version..

@milekz forked and added HIVE support 15days ago here is the fork https://github.com/milekz/NemosMiner-v2.5.2-HIVE

sorry i can not be more help atm once v3.0 is officially released i should have more time to start testing and working on Linux support

Best Regards
Nemo

**Comment by tiotoi** [comment]
@nemosminer Thanks a lot! you are doing a great job
