### ISSUE TITLE
BlazePool and MPH not reporting profit

### ISSUE THREAD

**Issue by Tesla74** [MrPlusGH/NPlusMiner#39]
BlazePool and MPH not reporting profit.  It is showing up on their API/Wallet websites.
I think there maybe an issue with NiceHash reporting profit also, but didn't mine long.

**Comment by MrPlusGH** [comment]
Blazepool is supported but i've seen their API not playing well some times. Working at this time my side.
Nicehash is supported for Earning Trackings and works my side.
MPH is not supported for Earnings Tracking yet.

Earning data are polled every 10 minutes. So we'd need to wait a bit to see projections.

**Comment by Tesla74** [comment]
After 8 hours.. finally got a report from Blaze.. estimates are way high
