### ISSUE TITLE
GUI worker name with multiple pools

### ISSUE THREAD

**Issue by Tesla74** [MrPlusGH/NPlusMiner#40]
If you are running multiple pools including MPH, then you have a problem with the worker name as MPH doesn't use "ID=".  I know there is a work around by using the PoolsConfig.json file, but issue if just using GUI.  I think "ID=" should somehow be moved to code.

**Comment by MrPlusGH** [comment]
Thank you!
Tagging as improvement.

**Comment by Tesla74** [comment]
Close this issue with the new issue,"Worker name - Deal with "ID=" in code", opened?

**Comment by MrPlusGH** [comment]
Somewhat fixed in 2.1.2 for NH and MPH but requires a nicer solution
#43
