### ISSUE TITLE
2 miner thread started instead of 6

### ISSUE THREAD

**Issue by RobinMM** [MrPlusGH/NPlusMiner#42]
Hi there,

When I download a new version, after configuring and starting, it will only start a 2 miner tread (while 6 gpu's are selected). I need to close the GUI and reopen. Then when I press start it will start 6 miner threads. This only happens during the initial setup.

![2tread](https://user-images.githubusercontent.com/1236301/37655329-3b9fa362-2c45-11e8-9697-12896b47bfea.jpg)

**Comment by MrPlusGH** [comment]
Thank you!
I will investigate to see if we have something wrong on first run.

**Comment by Shotfire** [comment]
I had the same problem. I had to make sure that after I clicked "Save Config" that I  closed everything and restarted. That seem to fix it.

**Comment by MrPlusGH** [comment]
Sorry to ask...
Are you sure you did hit Save Config on first run?
I cannot repro.

**Comment by Shotfire** [comment]
I have 6 rigs and I had to close and restart on everyone of them before they would mine with with all 8 cards. The config panel would detect all 8 but if I didn't do the re-start it would only mine with 2 cards

**Comment by MrPlusGH** [comment]
OK thank you.
Will keep investigating.

**Comment by MrPlusGH** [comment]
I am still failing to repro...

**Comment by MrPlusGH** [comment]
#78
