### ISSUE TITLE
Performance mode idea

### ISSUE THREAD

**Issue by Tesla74** [MrPlusGH/NPlusMiner#44]
This is just a feature idea.

Have two modes to choose from.  A safe mode that works with older cards and low chance of crash and a high performance mode that has fast miners, and works best with the newer cards.  That way everyone is happy.

A possible third mode could be to optimize for 7-12 gpus.

Possible way of implementing is by having a folder for each mode and point to folder of selected mode. 

Could also be called miner mode?

Possible folders:
Miners
--Safe
--High
--712
----Set1
----Set2

Bin
--Set1
--Set2

In the 712 folder there would be two sub folders for scripts.. one for one port and the other for another.
In the Bin folder there would be two sub-folders as Set1 runs one instance and Set2 runs the other.

**Comment by MrPlusGH** [comment]
I kind of have the same idea.
We should have a safe algo ist and a full algo list

**Comment by Tesla74** [comment]
I was thinking about miners.

A sample of how it would work with NeoScript:
Safe - CcminerKlaust
High - HSRminer

Safe: Works with all cards, old and new, and low chance of crashing on OC card.
High: Optimized for cards 1070 or higher.

**Comment by MrPlusGH** [comment]
Advanced users already have the ability to add/change miners.
Bringing this in the UI might make things way more complicated and confuse inexperienced users.

Still thinking about it...

**Comment by Tesla74** [comment]
I think that since you switched back the miners that the optional miners folder is good enough.

**Comment by MrPlusGH** [comment]
That is right.
The idea of NPlusMiner is to provide the more stable and best performances miners combination on the default configuration.
Keeping this in mind for the future though.
