### ISSUE TITLE
Explanation Request: brain plus config parameters

### ISSUE THREAD

**Issue by monkeyguy** [MrPlusGH/NPlusMiner#46]
Hey, wasn't sure where to post this so hopefully here is ok. I was seeing a lot of switching using zergpool plus and decided to try and decrease it. I doubled the sample size and trendspan size in the brain plus config xml, let it run overnight and saw increased profits today. I know there are many other factors involved, but would you mind explaining a bit how these parameters are meant to change the switching end result, I'd like to play around with them a bit more, but don't really understand what they do. LIke pros, cons of increasing/decreasing each? Also, what does sample half power do?

your work is much appreciated

**Comment by MrPlusGH** [comment]
I did not fin the time to document BrainPlus config option.
I'll try to find some time to do so.
Two thing to note for now.
 1 - TrendSpan is actually not used in current version so... doesn't change anything
 2 - Sample size is kind of the brain "memory" and this as a real impact.

Will try to document in the future but happy to see someone who wants to experiment and share!

**Comment by MrPlusGH** [comment]
;)
https://github.com/MrPlusGH/NPlusMiner-Documentation/wiki/BrainPlus-configuration-options
