### ISSUE TITLE
NplusMiner 2.1.3 include.ps1 argumentexception

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#51]
Hi,
 
PC crash rebooted, since then getting various errors when launching NPlusMiner 2.1.3. Been starting for more than 15 mins now, not yet done.
Need developer support to solve those issues, please help. The below errors are printed

**********************
Windows PowerShell transcript start
Start time: 20180329113658
Username: DESKTOP-67Q2PV4\DBminer
RunAs User: DESKTOP-67Q2PV4\DBminer
Configuration Name: 
Machine: DESKTOP-67Q2PV4 (Microsoft Windows NT 10.0.16299.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -version 5.0 -executionpolicy bypass -windowstyle maximized -file .\NPlusMiner-v2.1.ps1
Process ID: 6980
PSVersion: 5.1.16299.251
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.251
BuildVersion: 10.0.16299.251
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:210 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json
+                                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:210 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json
+                                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

Finding available TCP Port
PS>TerminatingError(New-Object): "Exception calling ".ctor" with "2" argument(s): "No connection could be made because the target machine actively refused it 127.0.0.1:4068""
Miners API Port: 4068
Starting Brains for Plus...
Starting Earnings Tracker...
Starting Cycle
Loading BTC rate from 'api.coinbase.com'..
PS>TerminatingError(ConvertFrom-Json): "Invalid JSON primitive: ."
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:210 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json
+                                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
ConvertFrom-Json : Invalid JSON primitive: .
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:210 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json
+                                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

Loading pool stats..
Cannot convert null to type "System.DateTime".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:117 char:5
+     $Stat = [PSCustomObject]@{
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : nullToObjectInvalidCast
Cannot convert null to type "System.DateTime".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:117 char:5
+     $Stat = [PSCustomObject]@{
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : nullToObjectInvalidCast

Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:134 char:5
+     $Span_Minute = [Math]::Min(($Date - $Stat.Updated).TotalMinutes,  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:134 char:5
+     $Span_Minute = [Math]::Min(($Date - $Stat.Updated).TotalMinutes,  ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:135 char:5
+     $Span_Minute_5 = [Math]::Min((($Date - $Stat.Updated).TotalMinute ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:135 char:5
+     $Span_Minute_5 = [Math]::Min((($Date - $Stat.Updated).TotalMinute ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:136 char:5
+     $Span_Minute_10 = [Math]::Min((($Date - $Stat.Updated).TotalMinut ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:136 char:5
+     $Span_Minute_10 = [Math]::Min((($Date - $Stat.Updated).TotalMinut ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:137 char:5
+     $Span_Hour = [Math]::Min(($Date - $Stat.Updated).TotalHours, 1)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:137 char:5
+     $Span_Hour = [Math]::Min(($Date - $Stat.Updated).TotalHours, 1)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:138 char:5
+     $Span_Day = [Math]::Min(($Date - $Stat.Updated).TotalDays, 1)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:138 char:5
+     $Span_Day = [Math]::Min(($Date - $Stat.Updated).TotalDays, 1)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:139 char:5
+     $Span_Week = [Math]::Min((($Date - $Stat.Updated).TotalDays / 7), ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
Cannot find an overload for "op_Subtraction" and the argument count: "2".
At C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Include.ps1:139 char:5
+     $Span_Week = [Math]::Min((($Date - $Stat.Updated).TotalDays / 7), ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Computing pool stats..
Loading miners..
Comparing miners and pools..
Launching Prerun: .\Prerun\X16r.bat
Starting miner
      1BTC = 6113 EUR
The process cannot access the file 'C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Config\poolapiref.json' because it is 
being used by another process.
    + CategoryInfo          : OpenError: (:) [Out-File], IOException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
    + PSComputerName        : localhost
The process cannot access the file 'C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Config\poolapiref.json' because it is being used by another process.
    + CategoryInfo          : OpenError: (:) [Out-File], IOException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
    + PSComputerName        : localhost

The process cannot access the file 'C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Config\poolapiref.json' because it is 
being used by another process.
    + CategoryInfo          : OpenError: (:) [Out-File], IOException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
    + PSComputerName        : localhost
The process cannot access the file 'C:\Users\DBminer\Desktop\NPlusMiner-2.1.3\Config\poolapiref.json' because it is being used by another process.
    + CategoryInfo          : OpenError: (:) [Out-File], IOException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
    + PSComputerName        : localhost

**Comment by MrPlusGH** [comment]
Seems like some files got corrupted during the crash.
Re-downloading NPlusMiner and start fresh should fix.
