### ISSUE TITLE
X16s algo on zergpool?

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#52]
Any plans to add newly added X16s algo to NplusMiner?There is an announcement on bitcointalk forum.

Thanks!

**Comment by nemosminer** [comment]
can add support but as its a very new coin it is not on any big exchanges yet, therefore 
"Pigeon (x16s)(no autotrade) by zergpool" http://zergpool.com/site/mining

**Comment by MrPlusGH** [comment]
Added. No autoexchange yet but NPlusMiner will pick it up when available.

**Comment by ebojali** [comment]
Cool, great and thanks alot! :)

**Comment by ebojali** [comment]
Autotrade on X16s enabled now but the NplusMiner did not pick it up since it wasn't included in the config.json algorith list, once added there it started the benchmark.
