### ISSUE TITLE
Inconsistent Benchmarking Results

### ISSUE THREAD

**Issue by rander2009** [MrPlusGH/NPlusMiner#55]
![20180331_074137](https://user-images.githubusercontent.com/36855890/38163335-f25f0ec4-34b7-11e8-810b-2228e59f777d.jpg)

Good day.  I have an issue, not sure if it's related to the miner or the pool.  Attached is a photo of two 5 GPU instances running on my 10 GPU (1080Ti) machine (same model GPUs) with no OC.  Prior to benching the stats folder was wiped clean, and both instances were executed simultaneously.

Why aren't the benchmark results the same or at least very similar? x17 has approximately a 30% difference between the two instances.

**Comment by Tesla74** [comment]
From the screenshot, it looks like both instances are set to GPUs 0,1,2,3,4.  Set one to 5,6,7,8,9.

**Comment by rander2009** [comment]
ok, thank you, that explains a few things !! ;)  i assumed (wrongfully) that setting 5/5 would do that.  Where is the best place to do this?  do i have to set for each algorithm?  i tried 0,1,2,3,4 in the GPU box but it doesn't work that way ;)

**Comment by Tesla74** [comment]
I'm assuming you have two complete copies of NPM.. one A and one B
Stop both copies and make these changes:

In copy "a" edit these lines in the config.json file located in the config folder
    "SelGPUCC":  "0,1,2,3,4",
    "SelGPUDSTM":  "0 1 2 3 4",
and in copy "b"
    "SelGPUCC":  "5,6,7,8,9",
    "SelGPUDSTM":  "5 6 7 8 9",

Remember to run the ResetBenchmark.bat for each copy before restarting.

**Comment by rander2009** [comment]
Ok, thank you, works good ;) 

Also - off topic a bit..  With nvidia inspector, can i set all GPUs with one command line? Or one command line per GPU. 

Thank you again. 

Sent from MailDroid

-----Original Message-----

**Comment by Tesla74** [comment]
I don't know NI very well.. still learning that myself.  Maybe MrPlus can answer.

**Comment by rander2009** [comment]
Thank you for your help, sincerely appreciated. 

Sent from MailDroid

-----Original Message-----

**Comment by rander2009** [comment]
Opps...  Whenever I hit save config it overwrites my edits in the b copy.  But it overwrites with 0,1,2,3,4.  Not 0-9..  Coding is not my Forte.. 

Sent from MailDroid

-----Original Message-----

**Comment by Tesla74** [comment]
Yep.  I forgot to mention that.  After manual edits to config.json, you'll need to continue to edit other settings manually because the Save Config in the GUI will overwrite.

**Comment by rander2009** [comment]
Ok ;) 

Sent from MailDroid

-----Original Message-----
