### ISSUE TITLE
UI lock up

### ISSUE THREAD

**Issue by trastek92** [MrPlusGH/NPlusMiner#56]
I am running 2.1.3 with 2.1.1 miners, but the issue I am having is while it still mines, it doesn't seem to update correctly, and the console works, but when I try to view the UI it either doesn't come up, or says not responding. Any suggestions? Has happened on all 3 of my machines.  So I end up restarting it and it will work for a while, then I go to check on it again and the UI is not responding.

**Comment by MrPlusGH** [comment]
The UI is generally not responsive while updatading the pools data. This is a known issue.
It becomes responsive again after that. Just need to wait a little bit. If you have a lot of pool enable, it might be longer to respond.

**Comment by trastek92** [comment]
Was running 2 pools at Max, and now just 1 pool again.  Will say powershell not responding.

**Comment by MrPlusGH** [comment]
#78
