### ISSUE TITLE
sha256t profitability calculated in a worng way. 

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#58]
Looks like this: 
![snip20180401_9](https://user-images.githubusercontent.com/35561346/38177804-5748ef22-3606-11e8-9769-c2f048088a79.png)

After consulting with zpool: 
The profitability factor for sha256t is Peta-Hash/sec, not GH. So divide your profit by 1000.

Could we please have an update on this, I am using 2.2 version.

**Comment by MrPlusGH** [comment]
Thank you!
Will fix in next version

**Comment by Tesla74** [comment]
Also may need to add  "sha256t": "SHA256t", to Algorithms.txt

**Comment by MrPlusGH** [comment]
Fixed in dev. Will be in next version.
