### ISSUE TITLE
CPU GPU load on kaby lake Celeron g3930?

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#59]
Hi,

This issue is reported on version 2.1.3

The NplusMiner 2.1.3 causes the GPUs to stall (I have a 7 1080Ti Rig) when the 120sec interval cycle kicks in, I've tried algos like X17, hsr, C11, skein and you could see the difference in GPU load behavior in the graphs below when comparing NplusMiner towards single algo mining. When the cycle is done the GPU load gets back to normal again. It is like the miner stalls during that time. I believe we need a fix for this to increase our profits using the NplusMiner because I think it is a great application. Hope to see this issue addressed soon. In the graphs you can see intervals of two minutes as the default interval setting in config file. If it is not clear I hope I could have a chat with you in a discoord channel or something. 

Mining hsr only with NplusMiner, don't mind the last part of the picture I stopped the miner before I took the screenshot:
![snip20180403_14](https://user-images.githubusercontent.com/35561346/38275630-bfce6ada-3792-11e8-86ed-2507e4afc34b.png)

Mining hsr single algo, with no NplusMiner:
![snip20180403_15](https://user-images.githubusercontent.com/35561346/38276569-af1e5094-3795-11e8-92c6-a51c1c39285c.png)

Also below you could see the CPU load (Intel Celeron Kaby Lake G3930), spikes to 100% when cycle executes, while not even close to 100% when mining without NplusMiner. I've tried other algo switching applications that does not have the same behavior. Something is fishy to me.

Mining hsr with NplusMiner:
![snip20180403_17](https://user-images.githubusercontent.com/35561346/38277280-2b2d339c-3798-11e8-8686-e0e41f1a0771.png)

Mining hrs single algo, with no NplusMiner, please refer to the last 5 minst. around 65%
![snip20180403_18](https://user-images.githubusercontent.com/35561346/38277576-319f1a78-3799-11e8-81de-d81767c7008d.png)

Regards
//Bojan

**Comment by ebojali** [comment]
I took a better picture illustrating the gpu load dropping when cycle kicks in and CPU load sky rockets. Also verified that I loose hashes when this happens.  Green line is the CPU load...
![screenshot_20180404-085704](https://user-images.githubusercontent.com/35561346/38293129-a50270ee-37e6-11e8-8fa5-f1a1f8d73930.png)

**Comment by MrPlusGH** [comment]
Thanks much for the detailed report!

I'm failing to reproduce the behavior on my rigs with 2.2 so far but will investigate further.
I sometimes see a small dip on GPU0 only but it is negligible, nothing like what you do see.
Same on CPU. I have small usage spike when the cycle runs but nothing comparable like the high CPU usage your rig is showing. (I have bigger CPU though)

@nemosminer , could you try to reproduce on your test rigs?

**Comment by nemosminer** [comment]
yip i'll test and report back..  i have not noticed this on any of my rigs...

**Comment by ebojali** [comment]
Thanks alot guys, let me know if you need anything from my side! :) Tested 2.2 as well and got the same behavior.

**Comment by nemosminer** [comment]
https://www.twitch.tv/minerx117

cpu - Pentium G4400, 4gbddr4, 120gbssd, win10

6x 1080ti's 

running hsr on zergpool plus NemosMiner v3.0 same code as NplusMiner 2.1.3

**Comment by nemosminer** [comment]
@ebojali - miningpoolhub + 3 different plus pools? i notice your running 4 different pools at once i'd say that would use alot more cpu... than running one..

im finding zergpool to be the most profitable at the moment very quick adding new coins followed by ahashpool... your not really achieving anything running miningpoolhub, zerg, zpool, and ahashpool at once...

**Comment by ebojali** [comment]
@nemosminer I just tried with zergpoolplus only and interval of 5 min. It is still happening but the dip is smaller. Does this actually mean that you can't run NplusMiner on a Celeron G3930 CPU?  

CPU kaby lake Celeron g3930
8 GB ddr4
ASRock h110 pro BTC+
120gb ssd win 10
7 gtx 1080ti

![screenshot_20180405-083000](https://user-images.githubusercontent.com/35561346/38350508-dedef9e8-38ab-11e8-8ecc-5063ea6b99c8.png)

**Comment by nemosminer** [comment]
whats the graph of? which program are you using for that? my gpu utilization does not spike down like that....

**Comment by ebojali** [comment]
It is the CPU and GPU load.. green line is CPU load and is normally around 60% when the NplusMiner is sleeping, 300sec (5 min) the other colors are gpu load. When cycle kicks in the CPU spikes and GPU drops as you can see in the gaps each 5 mins. During this time the hashrate drops.

Do you have a Celeron CPU to test you SW on as well?

**Comment by nemosminer** [comment]
Pentium G4400 basically the same just clocked @ 3.3ghz instead of 2.9ghz... im only running 6x 1080ti tho not 7...

**Comment by nemosminer** [comment]
which program are you using to record graph data for cpu and gpu's utilization?  id like to run the same in real time on my twitch stream

**Comment by ebojali** [comment]
I use the application http://openhardwaremonitor.org/. Make sure to klick in CPU total and GPU core load in the Load section. Then go to the view->show graph

![screenshot_20180405-121144](https://user-images.githubusercontent.com/35561346/38360470-8e7622dc-38ca-11e8-9250-9bfc355c17bd.png)

**Comment by MrPlusGH** [comment]
Here what i see with the same tool mining hsr on a 2x1070 test rig. NPlusMiner 2.2 running since more than 6 days
With 3 pools activated (2 Plus / 1 non plus)

![image](https://user-images.githubusercontent.com/36303784/38362678-0380f42e-38d2-11e8-8e2a-3d1d740a87d4.png)

![image](https://user-images.githubusercontent.com/36303784/38362884-bb39c032-38d2-11e8-90c7-feee6bda3075.png)

Long cpu 'spikes' (20% - would be 80% on one core) are NPlusMiner main cycle.
Short ones are BrainPlus jobs

I do not get what keeps your cpu at 60% minimum.
Do you have anything else running?
CPU mining?

**Comment by ebojali** [comment]
When I stop NplusMiner the CPU usage drops down to around 20% but as soon as I start mining the system process jumps up to around 45-50% and stays there as long as I mine.  Could you try the application on you 6 1080ti rig? No CPU mining I checked all the processes running.

I did a simple test now, as soon as the miners start the system process jumps and then then every cycle powershell jumps as well and then the hashes goes down becuase of the CPU util. Should really Powershell consume so much CPU power?

![capture](https://user-images.githubusercontent.com/35561346/38389205-fa9de82a-391d-11e8-8140-c7edf28368be.PNG)

**Comment by nemosminer** [comment]
are you running a Legit copy of windows 10? 
all MB drivers update to date? 
your cpu usage should not be that high.. 
if your cpu is using 20% when idle something is wrong with your OS.. 
also MSI afterburner is known to cause problems

**Comment by ebojali** [comment]
Windows is a downloaded activated version. 
All my MB drivers are updated as well as Bios.

I will try with one GPU only and add more and more until this issue occurs, also after that I will reinstall windows again and see how it behaves. I will update you.

Could you please take a look what happens in your larger 1080Ti rig when the cycle kicks in?

**Comment by MrPlusGH** [comment]
I am closing this one as we've been both investigating and are not able to repro.
Please keep us aware of any findings you might have and we'll re-open if required.
Thank you

**Comment by ebojali** [comment]
Please keep it open instead, I would like to see nemos look at the CPU util on the larger rig before. I don't feel that you have put any effort to try figure out what could be the issue and you have not ruled out that nplusminer does something, even if the CPU util shoots to the sky when cycle kicks in perhaps things can be done differently so that low ends CPU can coope with the application as well. Personally I don't see why this application should cause more CPU load than other auto swithing application I've tried...

**Comment by rander2009** [comment]
Move on, if cpu utilization is a problem - spend and extra $40 and get a new one. You'd be money ahead for the time spent on this issue.  FWIW I don't use any thing less than i3-7100. 

Sent from MailDroid

-----Original Message-----

**Comment by MrPlusGH** [comment]
Closing it doesn't mean we stop looking into it.
This is honestly the first report of such issue so might as weel be an issue on your side.

Keep us posted.

**Comment by ebojali** [comment]
Thanks. I will keep you posted. The plan is as follows

1. Try NplusMiner on my friends 8 1080 rig (not 1080 Ti). He has the same processor
2. Try with one gpu and add one at a time and see if there is a magic limit or any HW issues like risers broken
3. Reinstall the rig and try again

I will keep you posted!

Cheers!

**Comment by ebojali** [comment]
Just to update on bullet 1. I did install NplusMiner on his rig and it is the same behavior there's although not as bad symptoms the 100% CPU spike is quite short compared to mine..  next I will reinstall my rig

**Comment by ebojali** [comment]
Update on bullet 3, I did reinstall the system and there is no improvements.. Every time the Cycle starts  the CPU utilization goes to 100% ( blue line in the graph), the GPU load on the core decreases and looses hashrate, see graph below.. The interval is set to 120s. The conclusion from this study is that Kable lake processor G3930 2.9Ghz can't cope with NplusMiner application. I guess this is an eyecatcher for the developers to see what could be done as many miners out there probably use this low power consuming CPU. 

@MrPlusGH I find it very unfortunate that the Celeron processor is not enough for the NplusMiner.. Perhaps there is a use case to try improving the CPU util a bit?

![snip20180413_6](https://user-images.githubusercontent.com/35561346/38758231-51aa1a00-3f70-11e8-88cb-0fa904477660.png)

**Comment by ebojali** [comment]
additional comments, I changed the interval to 300 sec and  feel it is the same still. I think we should be prioritizing this issue. In the end we do donate (in my case the maximum) so I would expect some support etc. Below you can see an 10 min graph with interval set to 300 sec.. We clearly see that we doo allocate some 100% CPU when we start the cycle... Please update.. 

![snip20180414_8](https://user-images.githubusercontent.com/35561346/38760123-d75a4766-3f79-11e8-8a46-95bd33b584c1.png)

**Comment by ebojali** [comment]
Hi  @MrPlusGH  @nemosminer @rander2009 I've just change the processor to a Kaby Lake i3 7100 processor and it behaves much better.. CPU util is low (light green line) and It is keeping the hashes during the cycle with no drops, see picture below that contains a snapshot of 30mins mining and compare it to my previous pictures pasted. The dips you see is because of algo change, Works like a charm!
![snip20180418_14](https://user-images.githubusercontent.com/35561346/38957677-7c561922-435b-11e8-92eb-4d1240fb75e4.png)


Here is comparision of the two processors: https://ark.intel.com/compare/97452,97452,97455

So, if NplusMiner is going to be used I would never recommend going for an Intel Celeron G3930 since the calculations require some juice from the processor in order to not loose hashing power! (unless you have the possibility to improve the CPU util by coding)

Cheers!

**Comment by rander2009** [comment]
Awesome!  Glad it worked out for you & appreciate the data.  Always get what we pay for 😉
