### ISSUE TITLE
Scrypt hangs. Timeout bug

### ISSUE THREAD

**Issue by Olegik-ah** [MrPlusGH/NPlusMiner#60]
Hi!
Pls, have a look at https://github.com/nemosminer/NemosMiner/issues/496
As i understand - Nemo dont want to fix / dont understand me / dont understand how. 
Your code affected this bug too.

**Comment by MrPlusGH** [comment]
Not responding or not giving priority does not mean not understanding ;)

How many times did you see this happen?

invoke-restmethod has an indefinite timeout by default which doesn't mean infinite.

I'm not sure that this is an issue as this piece of code did not change in ages and this is the first occurrence of an issue we hear.

Still, it doesn't hurt to add so i'll queue this addition for next version.
Thank you

**Comment by Olegik-ah** [comment]
Hi!
Thanks for reply!
From documentation https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-5.1
-TimeoutSec
Specifies how long the request can be pending before it times out. Enter a value in seconds. **The default value, 0, specifies an indefinite time-out.**

I and my friend have 18 rigs (6 my + 12 friend). Most of them on 3G(mobile) internet. And it happens approx 5-7 times last month. Also script hangs on Invoke-WebRequest in pool.ps1.
For now i have added manually -TimeoutSec 15 in ALL Invoke-RestMethod and Invoke-WebRequest in ALL ps1 files. 1 week tested - no errors yet. I dont know difference between "indefinite" and "infinite", but my fix helped me.
Thanks!

**Comment by MrPlusGH** [comment]
Thank you for testing the solution.
As I said, will be implemented in next version.
