### ISSUE TITLE
Feature Request:  Specify a different btc address for Nicehash

### ISSUE THREAD

**Issue by nsummy** [MrPlusGH/NPlusMiner#64]
Since Nicehash will transfer BTC to a Coinbase wallet with zero fees it would be nice to specify a different address strictly for Nicehash.

**Comment by MrPlusGH** [comment]
NPlusMiner already include this feature, see: https://github.com/MrPlusGH/NPlusMiner/blob/master/README.md

Per pools config (Advanced)

- **This is for advanced users. Do not use if you do not know what you are doing.**
- You can now set specific options per pool. **_For example, you can mine NiceHash on the internal wallet and other pools on a valid wallet. This configuration is provided as an example in Config\PoolsConfig-NHInternal.json_**
- Available options
- Wallet = your wallet address
 - UserName = your MPH user name
 - WorkerName = your worker name
 - PricePenaltyFactor = See explanation below
- Usage
- The file Config\PoolsConfig.json contains per pool configuration details. If a pool is listed in this file,
    the specific settings will be taken into account. If not, the setting for the entry name default will be used.
    **Do not delete the default entry.**
        - Edit Config\PoolsConfig.json
        - Add an entry for the pool you want to customize
          - The name must be the NPlusMiner name for the pool. ie. for ahashpool, if you use Plus. The name is ahashpoolplus.
          - (**careful with json formating ;)**)
          - Best way is to duplicate the default entry
    - Note that the GUI only updates the default entry. Any other changes need to be done manualy
