### ISSUE TITLE
Invalid JSON primitive

### ISSUE THREAD

**Issue by ngasep** [MrPlusGH/NPlusMiner#68]
ConvertFrom-Json : Invalid JSON primitive: .
At D:\Download\NPlusMiner-2.2\Include.ps1:210 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json
+                                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : Invalid JSON primitive: .
At D:\Download\NPlusMiner-2.2\Include.ps1:210 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json
+                                           ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : Invalid JSON primitive: .
At D:\Download\NPlusMiner-2.2\Include.ps1:210 char:43
+             $Content = $_ | Get-Content | ConvertFrom-Json

What wrong with this

**Comment by MrPlusGH** [comment]
You must have some corrupted files in your stats folder.
Run ResetProfit.bat and restart.

If not fixed, run ResetBenchmark.bat and restart.

This should fix your issue.

This sometimes happen after a Rig crash.

Let us know if that fixes it.
