### ISSUE TITLE
earnings tracker displsyng negative values

### ISSUE THREAD

**Issue by geckah** [MrPlusGH/NPlusMiner#7]
have been running 1.3.2 for half a day and this is what the earnings tracker is displaying
zpoolplus Balance= 0.00271191 108%
Trust Level                      100% [ 00 days 11:12 ]
Average BTC/H                    BTC = -0.00013630 | mBTC = -0.136
Average BTC/D                    BTC = -0.00327123 | mBTC = -3.271
Estimated Pay Date               25/02/2018 10:00:00 > 0.0025 BTC

two other rigs are showing different but negative btc/day values

**Comment by MrPlusGH** [comment]
This means zpool reporting a balance lower than the previous one. This sometimes happen. Mainly due to orphaned or bad blocks at pool.
