### ISSUE TITLE
Missing explanation of earning tracker CSV files

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#70]
Hi.

It would be great if you Cold att an explanation tab of each column in your earning trackers CSV files that are generated or that you update your wiki page with an explanotiry section of the Excel files created.

**Comment by ebojali** [comment]
I cannot tell how much I earn daily on each pool I mine so I am looking forward for a column explanation of the sheets.

**Comment by MrPlusGH** [comment]
I'll find some time to document this in the help wiki.
Not on my priority right now though.
Not forgetting you, it will be done.

**Comment by MrPlusGH** [comment]
Still lacking time to spend on doc. Any help much appreciated.
https://github.com/MrPlusGH/NPlusMiner-Documentation/issues/3

**Comment by ebojali** [comment]
Would gladly help out if I could.. unfortunately I don't understand the columns in the CSV files.
