### ISSUE TITLE
mbtc_mh_factor

### ISSUE THREAD

**Issue by nemosminer** [MrPlusGH/NPlusMiner#71]
https://github.com/nemosminer/NemosMiner/issues/625

	switch ($zergpool_Algorithm) {
		"equihash" {$Divisor /= 1000}
		"blake2s" {$Divisor *= 1000}
		"blakecoin" {$Divisor *= 1000}
		"decred" {$Divisor *= 1000}
		"keccak" {$Divisor *= 1000}
		"keccakc" {$Divisor *= 1000}
		"yescrypt"{$Divisor /= 1000}
                "yescryptr16"{$Divisor /= 1000}

**Comment by MrPlusGH** [comment]
Thank you!
Fixed in 2.2.1
