### ISSUE TITLE
skein estimates moved to mBTC/GH/Day causing miner to stuck on skein algo

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#72]
skein estimates moved to mBTC/GH/Day - please dot he needful and adjust your profit switching miners accordingly. We need a fix for this asap..

![snip20180615_1](https://user-images.githubusercontent.com/35561346/41487557-7498e726-70e9-11e8-948d-8dcb6d702980.png)

**Comment by ebojali** [comment]
issue fixed by adding following row in pools <poolname>plus.ps1 file (if using plus functionality of course): 
"skein" {$Divisor *= 1000}

**Comment by ebojali** [comment]
The same happened for Nist5 now..

**Comment by MrPlusGH** [comment]
Fixed in 2.2.1
