### ISSUE TITLE
Ahashpool mBTC/Mh/day to mBTC/Gh/day!

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#73]
On ahashpool page: Announcement: [2018-06-24 16:20 UTC] Similar to other pools, to show more sig figs for precision, we will be moving algos: keccak, keccakc, x13, nist5, lbry, skein, from mBTC/Mh/day to mBTC/Gh/day on July 1st 2018. Most auto switching scripts authors have updated their software, please make sure you update to their latest build that reads the correct units from the pool's API.

**Comment by MrPlusGH** [comment]
Thank you!
Fixed in 2.2.2
