### ISSUE TITLE
Master = 4.0 for testers

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner#78]
Master = 4.0 for test

Please help by testing.
Please log you issue as new issues (not in this one) and specify 4.0 when reporting issues.

_Use releases if your not willing to test._

### NPlusMiner 4.0

**IMPORTANT NOTES
This is a major update which includes a lot of changes.
          - Start with a fresh install
          - Do not bring over your configuration files
          - Run the Benchmark (Do not copy your stats folder over)**

Why 4.0?
This is a huge release, see details below. We merged two release cycles to avoid too many updates on the user side.
NPlusMiner went through something close to a full architecture change and code rewrite resulting in a more reactive and even more stable product.
Upgrading to 4.0 to keep release cycle logic.

GUI Updates
 - Responsive GUI
   - No more "Not responding" or "spinning donut".
   - Fixed GUI lags 
 - Changed running miners to table view (CPU/NVIDIA)
 - Added Last 1hour/6hours/24hours earnings
   - Sign tells if above or below average over current sample
 - Added CPU/NVIDIA focus checkboxes on Switching tab

Optimized memory management
 - NPlusMiner will comsumes less memory after long runtime.

AutoUpdate feature
 - NPlusMiner now integrates an AutoUpdate feature enabled by default.
 - NPlusMiner fully handles updates and restarts itself when updates requires it. Not all updates will require a restart. We reviewed code structure so most updates do not require a restart. To summarize, only updates impacting the UI will require a restart. Other updates will be picked up dynamically.
 - Notes on AutoUpdates:
   - New versions will not be candidate to AutoUpdate as soon as released. There will be a time left so users can manually update. New versions will be set as candidate for AutoUpdate once early adopters' feedback will be received and version stabilized.
   - IMPORTANT
     - Deactivate AutoUpdate if you have customized miners or pools files. Autoupdate might overwrite these files on updates.
 - Security. AutoUpdates are:
   - Served from GitHub
   - Announced from a second different server
   - Verified with CRC provided from a third different source
   - The above provides three layers of protection
 - AutoUpdate can be disabled in config.
	What AutoUpdate won't do:
   - Won't update if ManualConfig is set to true in config
   - Won't update if AutoUpdate is not selected in config
   
BrainPlus Jobs start
 - Previously, BrainPlus jobs were only started at startup. BrainPlus jobs are now started when required. This avoid the need for an application restart when adding Plus pools in config. Simply add the Plus pool you want at runtime, hit Save Config and wait for the next cycle.

Earnings Tracker Jobs start
 - Previously, Earning Tracker jobs were only started at startup. Earning Tracker jobs are now started when required. This avoid the need for an application restart when adding Plus pools in config. Simply add the Plus pool you want at runtime, hit Save Config and wait for the next cycle.

CPU mining (experimental)
 - Added CPU mining
 - Has been tested for more than 30 days with no issue noted.
 - Includes only a few miners for now, more to come.
 - Available algorithms include: YescryptR16,Yescrypt,m7m,lyra2z
 
Miners re-download on updates
 - Will now automatically redownload miners when Miner ps1 file is updated.

Multi Instance Improvement
 - Port detection now has no impact on running miners.
 - Multi Instance still requires two separated copies of NPlusMiner in different folders.
 
Timeout in web requests
 - Some users reported issues with web request hanging on slow connections. Timeout added in all web request to avoid such issues.
 
Fixed wrong GPU selection on first running
 - NPLusMiner was selecting the wrong list of GPU after GPU count detection on first run only. This is now fixed.
 
Earnings Tracker interval
 - Earnings Tracker data poll interval was 10 minutes which was causing discrepencies on reported earning between different running instances of NPlusMiner. The poll interval has been lowered to 3 minutes to avoid this situation. 

Pools updates
 - Added PhiPhiPoolPlus, PhiPhiPool24hr, PhiPhiPool
 - Added BlockMastersPlus, BlockMasters24hr, BlockMasters
 - Added StarPoolPlus, StarPool24hr, StarPool
 - Added HashRefineryPlus, HashRefinery24hr
 
Miner Updates
 - Lots of updates on miner in this version
 - Re-benchmark is recommended
 - If full benchmark not wanted, you can copy your stats folder over and NPlusMiner will benchmark only when necessary.
 
Minor fixes
 - Fixed divisor on sha256t
 - Fixed manual config. You now need to set ManualConfig to true in Config.json.
 - Fixed console display
 - ...

**Comment by arminmacx** [comment]
Ok, Today i download your v4.0 version and when i start it and add blockmasters pool and try to load its default algos it games me this error. BTW at first when i run it it gave another error too :

`Get-content : Cannot find path 'C:\Users\armin\Desktop\Armin
mining\miner\NPlusMiner-master-4.0\NPlusMiner-master\Config\version.json' because it does not exist.
At C:\Users\armin\Desktop\Armin mining\miner\NPlusMiner-master-4.0\NPlusMiner-master\NPlusMiner.ps1:388 char:171
+ ... m-Json} catch {$Version = Get-content ".\Config\version.json" | Conve ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\armin\...ig\version.json:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-content : Cannot find path 'C:\Users\armin\Desktop\Armin
mining\miner\NPlusMiner-master-4.0\NPlusMiner-master\Config\PoolsAlgos.json' because it does not exist.
At C:\Users\armin\Desktop\Armin mining\miner\NPlusMiner-master-4.0\NPlusMiner-master\NPlusMiner.ps1:1127 char:250
+ ...  catch { $PoolsAlgos = Get-content ".\Config\PoolsAlgos.json" | Conve ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\armin\...PoolsAlgos.json:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand`

i check the folders and i saw there isn't any poolsalgo.ps1 or version.json in specified folder. i check the git source to chekc if my git forgot to download the files and i saw there aren't any file there like the app says.

**Comment by MrPlusGH** [comment]
These files are downloaded on first run and I cannot repro the issue.
Definitions for blockmasters algos where missing in the the file. This is now fixed.

**Comment by arminmacx** [comment]
Ok but i left the app almost 15 min but it didn't downloading anything?. my connection is ok no problem because i have nemosminer running for almost aweek

**Comment by MrPlusGH** [comment]
I just downloaded fresh from master, did a first run and I do not see this error.
Could try a fresh start again and confirm if you still have the issue?
Thanks for helping by testing

**Comment by arminmacx** [comment]
Ok i checked your code and see you point the app to a website tiny.cc which forward to another site which my antivirus block it and  now i see why it didn't download it. can you upload it to normal site instead the one you already point it. like github itsself

**Comment by MrPlusGH** [comment]
Thanks for the test and feedback.

This code has not changed since previous versions neither has the URL used. 
First time I hear about countries blocking these URLs. Interesting....

Redirects are used so file hoster could be changed in case of issues without requiring a product update. Without this, any problem with the hoster would break NPlusMiner and require a reinstall.

May I ask which country/Provider you use?

Please use #79 to track this one now.
