### ISSUE TITLE
URLs blocked in some countries ? Please report

### ISSUE THREAD

**Issue by MrPlusGH** [MrPlusGH/NPlusMiner#79]
@arminmacx

Ok, Today i download your v4.0 version and when i start it and add blockmasters pool and try to load its default algos it games me this error. BTW at first when i run it it gave another error too :

`Get-content : Cannot find path 'C:\Users\armin\Desktop\Armin
mining\miner\NPlusMiner-master-4.0\NPlusMiner-master\Config\version.json' because it does not exist.
At C:\Users\armin\Desktop\Armin mining\miner\NPlusMiner-master-4.0\NPlusMiner-master\NPlusMiner.ps1:388 char:171

    ... m-Json} catch {$Version = Get-content ".\Config\version.json" | Conve ...

                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        CategoryInfo : ObjectNotFound: (C:\Users\armin...ig\version.json:String) [Get-Content], ItemNotFoundEx
        ception
        FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-content : Cannot find path 'C:\Users\armin\Desktop\Armin
mining\miner\NPlusMiner-master-4.0\NPlusMiner-master\Config\PoolsAlgos.json' because it does not exist.
At C:\Users\armin\Desktop\Armin mining\miner\NPlusMiner-master-4.0\NPlusMiner-master\NPlusMiner.ps1:1127 char:250

    ... catch { $PoolsAlgos = Get-content ".\Config\PoolsAlgos.json" | Conve ...

                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        CategoryInfo : ObjectNotFound: (C:\Users\armin...PoolsAlgos.json:String) [Get-Content], ItemNotFoundEx
        ception
        FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand`

i check the folders and i saw there isn't any poolsalgo.ps1 or version.json in specified folder. i check the git source to chekc if my git forgot to download the files and i saw there aren't any file there like the app says.

UPDATE: about version.json you put it in root folder instead of config folder and because of that it gave the first error

**Comment by MrPlusGH** [comment]
@arminmacx

Ok i checked your code and see you point the app to a website tiny.cc which forward to another site which my antivirus block it and now i see why it didn't download it. can you upload it to normal site instead the one you already point it. like github itself

UPDATE: I disable my antivirus to see if its gonna work and this time my country block access to the site this time :D

**Comment by MrPlusGH** [comment]
Thanks for the test and feedback.

This code has not changed since previous versions neither has the URL used.
First time I hear about countries blocking these URLs. Interesting....

Redirects are used so file hoster could be changed in case of issues without requiring a product update. Without this, any problem with the hoster would break NPlusMiner and require a reinstall.

May I ask which country/Provider you use?

Please use #79 to track this one now.

**Comment by arminmacx** [comment]
well i didn't have any problem with previous version at all but this version after its redirect its blocked the file hosted site by antivirus and my country
I live in iran so they filter anything :D

**Comment by MrPlusGH** [comment]
could you try to access this directly?
http://sfiles.ucoz.org/sfiles/version.json

What is the error code in your browser?

**Comment by arminmacx** [comment]
exactly the link you provided is filtered in my country and by antivirus. no error by filtering it just says access to this site has been block

**Comment by arminmacx** [comment]
Ok this is very interesting if its true but i think its calculate badly. i will get 39$ per day with 3 1070ti and im the only miner on skien on blockmasters?
![screen shot 2018-07-04 at 23 18 30](https://user-images.githubusercontent.com/5224923/42291434-c969e01a-7fe0-11e8-8fb5-106f61a19e4b.png)
its been 6 hours and nothing changes on my blockmasters wallet

**Comment by MrPlusGH** [comment]
Anyone else is seeing this type of issue?

**Comment by nemosminer** [comment]
Iran Filters Everything im surprised he can access GitHub
