### ISSUE TITLE
4.0 - Bad calculation on brainplus + not responding

### ISSUE THREAD

**Issue by arminmacx** [MrPlusGH/NPlusMiner#80]
Ok this is very interesting if its true but i think its calculate badly. i will get 39$ per day with 3 1070ti and im the only miner on skien on blockmasters?
![screen shot 2018-07-04 at 23 18 30](https://user-images.githubusercontent.com/5224923/42291676-884748a0-7fe2-11e8-9225-bea10afdc840.png)

its been 6 hours and nothing changes on my blockmasters wallet
it is version 4 of nplusminer.

after 6 hours of working i see nplusminer stuck at not responding and i had to end task it

**Comment by MrPlusGH** [comment]
The hashrate for Skein on Blockmasters is really low (actually 0 as I write this) so the TTF must be more than 6 hours on this pool.

I encourage you to test on some other pool with more miners for the testing phase of 4.0.

Also, you must not select Blockmaster And BlockmasterPlus. You must use only one variant of each pool.

**Comment by MrPlusGH** [comment]
How did you get around your URL issue? VPN?

**Comment by arminmacx** [comment]
I use vpn on my own system and download the files and transfer it to nplusminer machine. im not using vpn on that machine for some reason.

**Comment by arminmacx** [comment]
Ok i tested on ahashpool too and as you suggest i only use ahashpoolplus this time and reset profit and benchmark and let it runs and benchmark and still its shows me skein algo most profit with 1700$ per day. 

BTW there is a bug and its when i stop the app and after few min when i hit start again its makes profits 0 and start mine algo which not even profit and after 120 sec later its still says 0 profit in everything and mine same algo
