### ISSUE TITLE
v4.0 initial testing results (errors)

### ISSUE THREAD

**Issue by nemosminer** [MrPlusGH/NPlusMiner#81]
downloaded master extracted 

left everything default (as you had it)

 click Start

it then gave these errors messages and does nothing just sits there

https://imgur.com/a/79W80DD

Regards
Nemo

**Comment by nemosminer** [comment]
fixed https://github.com/MrPlusGH/NPlusMiner/pull/82

**Comment by MrPlusGH** [comment]
Thank you.
Error was on line 339 which I modified today and was missing a curly bracket at the end

        If (($Variables.Miners | ? {($_.Pools.PSObject.Properties.Value.Price -ne $null) -or ($_.Pools.PSObject.Properties.Value.Price -gt 0)}).Count -gt 0) {$Variables.Miners = $Variables.Miners | ? {($_.Pools.PSObject.Properties.Value.Price -ne $null) -or ($_.Pools.PSObject.Properties.Value.Price -gt 0)}}

Fixed in master and tested.
