### ISSUE TITLE
Add Power consumption

### ISSUE THREAD

**Issue by rinkal26783** [MrPlusGH/NPlusMiner#85]
It would be nice to see power consumption stats along with Speed tab

**Comment by nemosminer** [comment]
NPlusMiner/Consumption/Consumption.json


[{
    "C11":  {
                "name":  "C11",
                "consumption":  245
            },
    "lyra2v2":  {
                    "name":  "lyra2v2",
                    "consumption":  255
                },
    "lyra2z":  {
                   "name":  "lyra2z",
                   "consumption":  255
               },
    "neoscrypt":  {
                      "name":  "neoscrypt",
                      "consumption":  255
                  },
    "ethash":  {
                      "name":  "ethash",
                      "consumption":  240
                  },
    "equihash":  {
                      "name":  "equihash",
                      "consumption":  240
                  },
    "x16r":  {
                      "name":  "x16r",
                      "consumption":  255
                  }
}]

**Comment by nemosminer** [comment]
Consumption/Readme.txt


Add the algorithm consumption in Watts.
If the algorithm doesn't exist it will assume that the consumption is 0 Watts

**Comment by nemosminer** [comment]
NPlusMiner.ps1

https://github.com/nemosminer/NemosMiner/blob/cab5da8953be6cc4d3db81e6cce1175f4c534cbd/NemosMinerv2.5.2.ps1

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/issues/399

**Comment by MrPlusGH** [comment]
We might look at implementing in the future but it is not in the short term list so far.
