### ISSUE TITLE
4.0.1 version benchmark issue!

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#87]
Hi, seems like a decimal issue in the benchmark results. see below picture. 9K as profit for lyra2z for example seems a little bit unlikely :) 
![snip20180707_2](https://user-images.githubusercontent.com/35561346/42411234-ded2ebee-81f8-11e8-99ed-112def3962b5.png)

**Comment by MrPlusGH** [comment]
Could you try to replace  .\pools\zpoolplus.ps1 with the file below and report?
You'll have to rename it from .txt to .ps1 fist.

[zpoolplus.txt](https://github.com/MrPlusGH/NPlusMiner/files/2172799/zpoolplus.txt)

**Comment by MrPlusGH** [comment]
Fixed ZpoolPlus divisor on master, will be updated in next version.

**Comment by ebojali** [comment]
@MrPlusGH 
I replaced the zploolplus.ps1 with your file and it does not work for me, it printed out an infinity sign.. 
 
![snip20180708_1](https://user-images.githubusercontent.com/35561346/42418014-0e354960-8297-11e8-9050-f8582439dc62.png)

**Comment by MrPlusGH** [comment]
I am so sorry,
There is a typo in the file I gave you. Line 21 says ZergPool when it should be Zpool

**Comment by ebojali** [comment]
Yes, now it works fine! Thanks!
