### ISSUE TITLE
brainplus has issue

### ISSUE THREAD

**Issue by arminmacx** [MrPlusGH/NPlusMiner#88]
We have serious issue right now with brainplus right now which when we use it it says i will get around 2000$ per day on ahashpool,blockmasters,zergpool and its never even close to that amount after 24 hours test. i reset everything and retried it but still shows same amount and its not good.

I report it few days ago but you just close it without even answer or helping to solve the issue

**Comment by MrPlusGH** [comment]
Does anyone else have this issue? Please report here.

I'm digging into this right now. Let me some time to find out.

No others reported this issue though.

**Comment by MrPlusGH** [comment]
Could you try the normal option (not Plus) on the same pool and report if you do see any issue this way?

Thanks for helping!

**Comment by arminmacx** [comment]
ok give me some time because now im mining with other app

**Comment by MrPlusGH** [comment]
Sad to hear this.
Happy to help if you can bring more info.

**Comment by arminmacx** [comment]
i will but why you close the issue so fast? its not just your app nemos app too its gave same result too

**Comment by MrPlusGH** [comment]
Nemo and I work together. We share the same code.
Issue is closed because you said you're moving to other app and no other user seems to have the same problem.
But your help is still much appreciated if you can help find what happens.

**Comment by arminmacx** [comment]
I know you and nemo works together and because of that i said both your code as its same have issue. i moved to bminer to mine zcash because i lose 3 days because false profit shows in your app. im still interested in your app and i love it but when i removed it and redownload it and tried again and see it gave me same amount of profit again again, i report the issue and move to make some profit.

who doesn't love to get profit of 2000$ per day with 3 GPUs but its not possible don't you agree?

im still go and test with normal and 24hr mode and report back
