### ISSUE TITLE
Separate Nicehash wallet

### ISSUE THREAD

**Issue by rinkal26783** [MrPlusGH/NPlusMiner#90]
most of us have different wallet address for nicehash. So. we can't use nicehash pool until we can add nicehash wallet to your miner.

**Comment by TGM8599** [comment]
You can add it to your PoolsConfig.json, and it will override the default wallet.

**Comment by MrPlusGH** [comment]
See Readme: https://github.com/MrPlusGH/NPlusMiner/blob/master/README.md

   Per pools config (Advanced)
   
        - **This is for advanced users. Do not use if you do not know what you are doing.**
        - You can now set specific options per pool. For example, you can mine NiceHash on the internal wallet and other pools on a valid wallet. This configuration is provided as an example in Config\PoolsConfig-NHInternal.json
          - Available options
            - Wallet = your wallet address
            - UserName = your MPH user name
            - WorkerName = your worker name
            - PricePenaltyFactor = See explanation below
          - Usage
            - The file Config\PoolsConfig.json contains per pool configuration details. If a pool is listed in this file,
	    the specific settings will be taken into account. If not, the setting for the entry name default will be used.
	    **Do not delete the default entry.**
            - Edit Config\PoolsConfig.json
            - Add an entry for the pool you want to customize
              - The name must be the NPlusMiner name for the pool. ie. for ahashpool, if you use Plus. The name is ahashpoolplus.
              - (**careful with json formating ;)**)
              - Best way is to duplicate the default entry
        - Note that the GUI only updates the default entry. Any other changes need to be done manualy
