### ISSUE TITLE
PasswordCurrency taken from Config file instead of poolsConfig for CryptoDredge

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#92]
Wallet address and password currency is set for LTC, but poolsconfig is configured as follows for blazepool:

    "blazepoolplus":  {
                          "UserName":  "DBminer",
                          "Wallet":  "19CHzK8ATbN7mXXXXXXXXXX,
                          "WorkerName":  "ID=rig1",
                          "PricePenaltyFactor":  1
                      },

The start command looks like this as you can see c=LTC instead of c=BTC. There might be more miners that are acting the same way so you can correct them all.
     Speed Started  Active   Cnt  Command
     ----- -------  ------   ---  -------
49.71 MH/s 00:00:24 00:00:24 Once VIDIA-CryptoDredge\CryptoDredge.exe  -b 127.0.0.1:4068 -d 0,1,2,3,4,5,6 -a phi2 --no-watchdog -o stratum+tcp://phi2.mine.blazepool.com:8332 -u 19CHzK8ATbN7XXXXXXXXXXXXXX -p ID=rig1,c=LTC -R 1 -q -N 1

Because of this issue no coins are recieved at my blazepool wallet..

**Comment by ebojali** [comment]
I believe that this line should be updated so that it sets BTC if a BTC adress is used in blazepoolplus.ps1 instead of reading the input from the general config..

Pass          = "$($Config.PoolsConfig.$ConfName.WorkerName),c=$($Config.Passwordcurrency)"

**Comment by MrPlusGH** [comment]
Fixed in 4.2 which is currently flowing through AutoUpdate.
Please test and report.

https://github.com/MrPlusGH/NPlusMiner/releases

**Comment by ebojali** [comment]
Seems to be working fine!
