### ISSUE TITLE
Yescryptr16 showing wrong profit

### ISSUE THREAD

**Issue by rinkal26783** [MrPlusGH/NPlusMiner#93]
Type: NVIDIA

Miner             Algorithm          Speed     mBTC/Day      BTC/Day      USD/Day   BTC/GH/Day Pool
-----             ---------          -----     --------      -------      -------   ---------- ----
ccminerKlausT     YescryptR16    7.18 KH/s      367.426      0.36743    2,460.249 51,173.68455 blockmastersplus-
ccminerTpruvot225 Lyra2z         7.28 MH/s        0.777      0.00078        5.205      0.10684 blockmastersplus-
ccminerx16s       HMQ1725       19.57 MH/s        0.710      0.00071        4.757      0.03630 zpoolplus-
ccminerTpruvot225 HMQ1725       19.29 MH/s        0.700      0.00070        4.688      0.03630 zpoolplus-
ccminerTpruvot23  Allium        15.70 MH/s        0.540      0.00054        3.619      0.03444 zergpoolplus-
ccminerPigeon     X16s          52.63 MH/s        0.532      0.00053        3.563      0.01011 zergpoolplus-
ccminerTpruvot225 Tribus       248.62 MH/s        0.494      0.00049        3.305      0.00199 blockmastersplus-
ccminerTpruvot23  Phi2          13.73 MH/s        0.441      0.00044        2.951      0.03209 zergpoolplus-
ccminerKlausT     Yescrypt      40.92 KH/s        0.292      0.00029        1.954      7.13295 zpoolplus-
EthashClaymore    Ethash      Benchmarking Benchmarking Benchmarking Benchmarking      0.00508 nicehash-

   Type: CPU

Miner               Algorithm         Speed mBTC/Day BTC/Day USD/Day   BTC/GH/Day Pool
-----               ---------         ----- -------- ------- -------   ---------- ----
CpuminerJayddeeSse2 YescryptR16 309.97  H/s   15.862 0.01586 106.213 51,173.68455 blockmastersplus-
CpuminerJayddeeSse2 Lyra2z      127.87 KH/s    0.014 0.00001   0.091      0.10684 blockmastersplus-
CpuminerJayddeeSse2 Yescrypt      1.25 KH/s    0.009 0.00001   0.060      7.13295 zpoolplus-
CpuminerJayddeeSse2 M7m          40.20 KH/s    0.006 0.00001   0.042      0.15481 zergpoolplus-
CpuminerJayddeeSse2 Allium      177.78 KH/s    0.006 0.00001   0.041      0.03444 zergpoolplus-
CpuminerJayddeeSse2 HMQ1725      75.68 KH/s    0.003 0.00000   0.018      0.03630 zpoolplus-

**Comment by rinkal26783** [comment]
![image](https://user-images.githubusercontent.com/30832110/42432673-4c7b97ba-8369-11e8-9024-2689037fbaad.png)

**Comment by MrPlusGH** [comment]
This is a pool issue not a NPlusMiner one.
Use another pool

**Comment by rinkal26783** [comment]
anyway i can modify?

**Comment by MrPlusGH** [comment]
No. The pool need to fix their API.
#94
