### ISSUE TITLE
normal mode of profit shows incredible profit for 3 gpus

### ISSUE THREAD

**Issue by arminmacx** [MrPlusGH/NPlusMiner#94]
Hi,

As i told you before the app shows unormal profit for 24 hours and this time i check with 4 different pool in normal mode (no plus or 24hr mode) this time. i attach the screen shot for you to see it.
this is latest release version of NpluMiner
![screen shot 2018-07-09 at 13 49 31](https://user-images.githubusercontent.com/5224923/42442298-8523e796-837f-11e8-957a-d59a8249035e.png)

**Comment by MrPlusGH** [comment]
Blockmasters API is reporting wrong estimations for YesscryptR16 see:

Zergpool:
{"name":"yescryptR16","port":6333,"coins":2,"fees":0.5,"hashrate":231997,"workers":154,"estimate_current":**"0.00004708"**,"estimate_last24h":"0.00005120","actual_last24h":"0.02011"**,"mbtc_mh_factor":0.001**,"hashrate_last24h":158594.625}}

Blockmasters:
{"name":"yescryptR16","port":6333,"coins":2,"fees":0.25,"hashrate":55943,"workers":138,"estimate_current":**0.0438727372**,"estimate_last24h":"0.04623037","actual_last24h":"0.03379"**,"mbtc_mh_factor":0.001**,"hashrate_last24h":55090.6042,"estimate_old":0.0438727372}}

I'd suggest you contact the pool.
in the meantime, either change pool or remove YescryptR16 from your algo list.
