### ISSUE TITLE
Cryptodredge wrong MPH username bug!

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#95]
Even though worker name and MPH username is filled in the config the cryptodredge miner still puts a dot in the -u argument. This gives an "unathorized" error. Seems like it is reading in the poolsconfig files which is in my case not configured.. config file.
![snip20180709_1](https://user-images.githubusercontent.com/35561346/42477512-ab842412-83d1-11e8-982a-14bece730269.png)

**Comment by MrPlusGH** [comment]
PoolsConfig.json should at least contains an entry named default if SaveConfig has been pressed.
Could you paste the content of the file?

**Comment by ebojali** [comment]
I noticed this only happens when the MPH API response but nothing from the other pools as you can see in the background console, in the GUI I've selected plus pools: zerg, zpool, ahash, blaze as well as NH but nothing for those pools on the algos. 

The content of the poolsconfig.json:
{
    "default":  {
                    "PricePenaltyFactor":  1,
                    "Wallet":  "19CHzK8ATbN7mNiv48fGnCnbLuzyitvEcC",
                    "UserName":  "DBminer",
                    "WorkerName":  "ID=rig1",
                    "APIKey":  "c6fb4a033d7279169d09caf707cc8a19d89fda807b9947491902ef47f2dd4b51"
                }
}

**Comment by ebojali** [comment]
checked the miner.log and it happened again during the night with MPH skein..
  6.51 GH/s 00:02:57 00:02:12 2    VIDIA-Alexis78\ccminer.exe -b 4068 -R 1 -a skein -o stratum+tcp://hub.miningpoolhub.com:17016 -u DBminer.rig1 -p x -N 1 -d 0,1,2,3,4,5,6

**Comment by ebojali** [comment]
@MrPlusGH Closed? Just happened again...

**Comment by MrPlusGH** [comment]
Please try 4.2, I reviewed all pool files in this version
