### ISSUE TITLE
4.2 update profit calculation decimal error

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#96]
Hi,

Please fix the calculation of profits in the 4.2 version, see picture attached. Seems to be a decimal error.

![snip20180712_3](https://user-images.githubusercontent.com/35561346/42602762-3b7460ec-856b-11e8-807c-4951aa7bbc48.png)

**Comment by MrPlusGH** [comment]
Done in 4.2.1
Flowing through AutoUpdate
